/*
 * ポケモンSV元ネタ推測図鑑 ― ファッション（服・小物・スマホロトムのカバー）
 * 本編（追加コンテンツ・ほかの作品のセーブデータ連動・配信を除く）で手に入る 129 点。
 * Bulbapedia「List of clothing in Pokémon Scarlet and Violet」で日英の名前と入手方法を照らし合わせています。
 * sub … 一覧で分けて表示するときの小分類
 */
var FASHION_ENTRIES = [
  { c: 'fashion', ja: 'せいふく（はる）', en: 'Spring Uniform', sp: 0, cf: 3, jo: '制服＋春', eo: 'spring＋uniform', ev: 'アカデミーの制服。季節ごとに4種類あり、スカーレットはオレンジ、バイオレットは紫が基調。', sub: '制服・上下', t: ['clothes'] },
  { c: 'fashion', ja: 'せいふく（なつ）', en: 'Summer Uniform', sp: 0, cf: 3, jo: '制服＋夏', eo: 'summer＋uniform', ev: '', sub: '制服・上下', t: ['clothes'] },
  { c: 'fashion', ja: 'せいふく（あき）', en: 'Autumn Uniform', sp: 0, cf: 3, jo: '制服＋秋', eo: 'autumn＋uniform', ev: '', sub: '制服・上下', t: ['clothes'] },
  { c: 'fashion', ja: 'せいふく（ふゆ）', en: 'Winter Uniform', sp: 0, cf: 3, jo: '制服＋冬', eo: 'winter＋uniform', ev: '', sub: '制服・上下', t: ['clothes'] },
  { c: 'fashion', ja: 'ジャージセットアップ', en: 'Tracksuit', sp: 1, cf: 3, jo: 'ジャージ（jersey）＋セットアップ（上下そろい）', eo: 'tracksuit（陸上競技用の上下）', ev: '日本語の「ジャージ」は英語の jersey（編んだ生地）から。英語では tracksuit と呼ぶ。', sub: '制服・上下', t: ['clothes'] },
  { c: 'fashion', ja: 'ハイソックス', en: 'High Socks', sp: 1, cf: 3, jo: 'high socks（ひざ下までの長い靴下）', eo: 'high socks', ev: '', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'スポーツハイソックス', en: 'Sporty High Socks', sp: 1, cf: 3, jo: 'sports＋high socks', eo: 'sporty＋high socks', ev: '', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'チェックがらハイソックス', en: 'Plaid High Socks', sp: 1, cf: 3, jo: 'check（格子柄）＋high socks', eo: 'plaid（格子柄。スコットランドの肩掛けから）', ev: '格子柄を日本語は「チェック」、英語は「プラッド」と呼んでいる。', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'はながらハイソックス', en: 'Floral High Socks', sp: 1, cf: 3, jo: '花柄＋high socks', eo: 'floral（花柄の）＋high socks', ev: '', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'クルーソックス', en: 'Crew Socks', sp: 1, cf: 3, jo: 'crew socks（くるぶし上の短めの靴下。ボートの漕ぎ手＝crew がはいたことから）', eo: 'crew socks', ev: '', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ボーダークルーソックス', en: 'Striped Crew Socks', sp: 1, cf: 3, jo: 'border（しま模様、和製英語的な使い方）＋crew socks', eo: 'striped＋crew socks', ev: '日本語の「ボーダー」は英語では stripe（しま）。', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ほしがらクルーソックス', en: 'Starry Crew Socks', sp: 1, cf: 3, jo: '星柄＋crew socks', eo: 'starry（星の）＋crew socks', ev: '', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'カラフルクルーソックス', en: 'Colorful Crew Socks', sp: 1, cf: 3, jo: 'colorful＋crew socks', eo: 'colorful＋crew socks', ev: '', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'フリルクルーソックス', en: 'Frilly Crew Socks', sp: 1, cf: 3, jo: 'frill＋crew socks', eo: 'frilly＋crew socks', ev: '', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'タイツ', en: 'Plain Tights', sp: 1, cf: 3, jo: 'tights', eo: 'plain（無地の）＋tights', ev: '', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'スポーツタイツ', en: 'Sporty Tights', sp: 1, cf: 3, jo: 'sports＋tights', eo: 'sporty＋tights', ev: '', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'プリントタイツ', en: 'Printed Tights', sp: 1, cf: 3, jo: 'print＋tights', eo: 'printed＋tights', ev: '', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'パターンタイツ', en: 'Patterned Tights', sp: 1, cf: 3, jo: 'pattern（柄）＋tights', eo: 'patterned＋tights', ev: '', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ゴージャスタイツ', en: 'Dazzling Tights', sp: 1, cf: 3, jo: 'gorgeous（豪華な）＋tights', eo: 'dazzling（まばゆい）＋tights', ev: '', sub: 'レッグウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'スクールスニーカー', en: 'School Shoes', sp: 0, cf: 3, jo: 'school＋sneakers', eo: 'school shoes', ev: '', sub: 'シューズ', t: ['clothes'] },
  { c: 'fashion', ja: 'ハイテクスニーカー', en: 'Performance Sneakers', sp: 1, cf: 3, jo: 'high-tech（最新技術の）＋sneakers', eo: 'performance（性能重視の）＋sneakers', ev: '', sub: 'シューズ', t: ['clothes'] },
  { c: 'fashion', ja: 'ローカットスニーカー', en: 'Low-Top Sneakers', sp: 1, cf: 3, jo: 'low-cut＋sneakers', eo: 'low-top＋sneakers', ev: '', sub: 'シューズ', t: ['clothes'] },
  { c: 'fashion', ja: 'ローファー', en: 'Loafers', sp: 1, cf: 3, jo: 'loafer（なまけ者。ひもを結ばずに履ける靴）', eo: 'loafers', ev: '', sub: 'シューズ', t: ['clothes'] },
  { c: 'fashion', ja: 'エンジニアブーツ', en: 'Engineer Boots', sp: 1, cf: 3, jo: 'engineer（機関士）の作業用ブーツ', eo: 'engineer boots', ev: '', sub: 'シューズ', t: ['clothes'] },
  { c: 'fashion', ja: 'レースアップシューズ', en: 'Dress Shoes', sp: 1, cf: 3, jo: 'lace-up（ひもで締める）＋shoes', eo: 'dress shoes（正装用の靴）', ev: '', sub: 'シューズ', t: ['clothes'] },
  { c: 'fashion', ja: 'スポーツサンダル', en: 'Sporty Sandals', sp: 1, cf: 3, jo: 'sports＋sandals', eo: 'sporty＋sandals', ev: '', sub: 'シューズ', t: ['clothes'] },
  { c: 'fashion', ja: 'ビーチサンダル', en: 'Flip-Flops', sp: 1, cf: 3, jo: 'beach＋sandal（和製英語「ビーサン」）', eo: 'flip-flops（歩くときのパタパタという音から）', ev: '日本語は和製英語、英語は音からきた言い方。', sub: 'シューズ', t: ['clothes'] },
  { c: 'fashion', ja: 'ハイカットスニーカー', en: 'High-Top Sneakers', sp: 1, cf: 3, jo: 'high-cut＋sneakers', eo: 'high-top＋sneakers', ev: '日本語は cut、英語は top。', sub: 'シューズ', t: ['clothes'] },
  { c: 'fashion', ja: 'スクールグローブ', en: 'School Gloves', sp: 0, cf: 3, jo: 'school＋gloves', eo: 'school＋gloves', ev: '', sub: 'グローブ', t: ['clothes'] },
  { c: 'fashion', ja: 'ゆびぬきグローブ', en: 'Fingerless Gloves', sp: 1, cf: 3, jo: '指抜き＋glove', eo: 'fingerless gloves', ev: '', sub: 'グローブ', t: ['clothes'] },
  { c: 'fashion', ja: 'デミグローブ', en: 'Fingerless Mittens', sp: 1, cf: 3, jo: 'demi（半分）＋glove', eo: 'fingerless mittens', ev: '', sub: 'グローブ', t: ['clothes'] },
  { c: 'fashion', ja: 'レザーグローブ', en: 'Leather Gloves', sp: 1, cf: 3, jo: 'leather＋gloves', eo: 'leather＋gloves', ev: '', sub: 'グローブ', t: ['clothes'] },
  { c: 'fashion', ja: 'カットアウトグローブ', en: 'Driving Gloves', sp: 1, cf: 3, jo: 'cut-out（くりぬいた）＋glove', eo: 'driving gloves（運転用の手袋）', ev: '', sub: 'グローブ', t: ['clothes'] },
  { c: 'fashion', ja: 'グローブ', en: 'Plain Gloves', sp: 1, cf: 3, jo: 'gloves', eo: 'plain＋gloves', ev: '', sub: 'グローブ', t: ['clothes'] },
  { c: 'fashion', ja: 'スクールリュック', en: 'School Backpack', sp: 0, cf: 3, jo: 'school＋rucksack（ドイツ語で背負い袋）', eo: 'school backpack', ev: '日本語の「リュック」はドイツ語の Rucksack から。', sub: 'バッグ', t: ['clothes'] },
  { c: 'fashion', ja: 'ナイロンリュック', en: 'Nylon Backpack', sp: 1, cf: 3, jo: 'nylon＋rucksack', eo: 'nylon＋backpack', ev: '', sub: 'バッグ', t: ['clothes'] },
  { c: 'fashion', ja: 'レザーリュック', en: 'Leather Backpack', sp: 1, cf: 3, jo: 'leather＋rucksack', eo: 'leather＋backpack', ev: '', sub: 'バッグ', t: ['clothes'] },
  { c: 'fashion', ja: 'キャンバスリュック', en: 'Canvas Backpack', sp: 1, cf: 3, jo: 'canvas（帆布）＋rucksack', eo: 'canvas＋backpack', ev: '', sub: 'バッグ', t: ['clothes'] },
  { c: 'fashion', ja: 'スポーツリュック', en: 'Sport Backpack', sp: 1, cf: 3, jo: 'sports＋rucksack', eo: 'sport＋backpack', ev: '', sub: 'バッグ', t: ['clothes'] },
  { c: 'fashion', ja: 'スクールハット', en: 'School Hat', sp: 0, cf: 3, jo: 'school＋hat', eo: 'school hat', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'スポーツキャップ', en: 'Sporty Cap', sp: 1, cf: 3, jo: 'sports＋cap', eo: 'sporty＋cap', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'キャスケット', en: 'Gatsby Cap', sp: 1, cf: 3, jo: 'casquette（フランス語で帽子）', eo: 'Gatsby（小説『グレート・ギャツビー』の時代の帽子）', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ビーニー', en: 'Beanie', sp: 1, cf: 3, jo: 'beanie（ぴったりしたニット帽）', eo: 'beanie', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ポンポンぼう', en: 'Pom-Pom Hat', sp: 1, cf: 3, jo: 'pompon（フランス語で玉飾り）＋帽', eo: 'pom-pom hat', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'マリンキャップ', en: 'Square Cap', sp: 1, cf: 3, jo: 'marine cap（船乗りの帽子）', eo: 'square cap', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ベレーぼう', en: 'Beret', sp: 1, cf: 3, jo: 'béret（フランス語）＋帽', eo: 'beret', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'なかおれハット', en: 'Fedora', sp: 1, cf: 3, jo: '中折れ帽', eo: 'fedora（戯曲『フェドーラ』から名付いた帽子）', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'バケットハット', en: 'Bucket Hat', sp: 1, cf: 3, jo: 'bucket（バケツ）形の帽子', eo: 'bucket hat', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'フライトキャップ', en: 'Trapper Hat', sp: 1, cf: 3, jo: 'flight cap（飛行士の帽子）', eo: 'trapper（わな猟師）の帽子', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ヘアバンド', en: 'Sweatband', sp: 1, cf: 3, jo: 'hair band', eo: 'sweatband（汗止めのバンド）', ev: '日本語は髪、英語は汗に注目した呼び方。', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ハンチング', en: 'Flat Cap', sp: 1, cf: 3, jo: 'hunting cap（狩猟用の帽子）', eo: 'flat cap（平たい帽子）', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ポーラーハット', en: 'Bowler Hat', sp: 1, cf: 3, jo: 'bowler hat（山高帽。帽子屋ボウラー兄弟の名前から）の日本語表記', eo: 'bowler hat', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'むぎわらぼう', en: 'Straw Hat', sp: 1, cf: 3, jo: '麦わら帽', eo: 'straw hat', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'スクールヘルメット', en: 'School Helmet', sp: 0, cf: 3, jo: 'school＋helmet。ライドのときにかぶる', eo: 'school helmet', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'エクスレッグヘルメット', en: 'Lokix Helmet', sp: 1, cf: 3, jo: 'エクスレッグ（ポケモン）＋helmet', eo: 'Lokix＋helmet', ev: 'ポケモンの顔を模したヘルメット。', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'フルフェイスヘルメット', en: 'Full-Face Helmet', sp: 1, cf: 3, jo: 'full-face（顔全体を覆う）＋helmet', eo: 'full-face helmet', ev: 'ライド用のヘルメット。', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'クールヘルメット', en: 'Cool Helmet', sp: 1, cf: 3, jo: 'cool＋helmet', eo: 'cool＋helmet', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'レトロジェットヘルメット', en: 'Retro Jet Helmet', sp: 1, cf: 3, jo: 'retro＋jet helmet', eo: 'retro＋jet helmet', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ジェットヘルメット', en: 'Jet Helmet', sp: 1, cf: 3, jo: 'jet helmet（顔の前が開いたヘルメット）', eo: 'jet helmet', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ハーフヘルメット', en: 'Half Helmet', sp: 1, cf: 3, jo: 'half helmet', eo: 'half helmet', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'レーシングヘルメット', en: 'Racing Helmet', sp: 1, cf: 3, jo: 'racing＋helmet', eo: 'racing helmet', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'オフロードヘルメット', en: 'Off-Road Helmet', sp: 1, cf: 3, jo: 'off-road＋helmet', eo: 'off-road helmet', ev: '', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'スポーツヘルメット', en: 'Cycling Helmet', sp: 1, cf: 3, jo: 'sports＋helmet', eo: 'cycling（自転車）＋helmet', ev: '日本語はスポーツ、英語は自転車用。', sub: 'ヘッドウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ウェリントングラス', en: 'Horn-Rimmed Glasses', sp: 1, cf: 3, jo: 'Wellington（ウェリントン公にちなむ眼鏡の形）', eo: 'horn-rimmed（べっこう縁の）', ev: '', sub: 'アイウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ウェリントンサングラス', en: 'Horn-Rimmed Sunglasses', sp: 1, cf: 3, jo: 'Wellington＋sunglasses', eo: 'horn-rimmed＋sunglasses', ev: '', sub: 'アイウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ハーフリムグラス', en: 'Half-Rim Glasses', sp: 1, cf: 3, jo: 'half rim（半分だけの縁）＋glasses', eo: 'half-rim glasses', ev: '', sub: 'アイウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ハーフリムサングラス', en: 'Half-Rim Sunglasses', sp: 1, cf: 3, jo: 'half rim＋sunglasses', eo: 'half-rim sunglasses', ev: '', sub: 'アイウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ロイドグラス', en: 'Round Glasses', sp: 1, cf: 3, jo: '喜劇俳優ハロルド・ロイドが掛けた丸眼鏡から', eo: 'round glasses（形そのまま）', ev: '日本語版は人名由来の呼び方、英語版は形の説明になっている。', sub: 'アイウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ロイドサングラス', en: 'Round Sunglasses', sp: 1, cf: 3, jo: 'ロイド（喜劇俳優ハロルド・ロイドの丸眼鏡）＋sunglasses', eo: 'round sunglasses', ev: '', sub: 'アイウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'スクエアグラス', en: 'Square Glasses', sp: 1, cf: 3, jo: 'square（四角）＋glasses', eo: 'square glasses', ev: '', sub: 'アイウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'スクエアサングラス', en: 'Square Sunglasses', sp: 1, cf: 3, jo: 'square＋sunglasses', eo: 'square sunglasses', ev: '', sub: 'アイウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ティアドロップサングラス', en: 'Aviator Sunglasses', sp: 1, cf: 3, jo: 'teardrop（涙のしずく形）', eo: 'aviator（飛行士。パイロット用の形から）', ev: '', sub: 'アイウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'オーバルグラス', en: 'Oval Glasses', sp: 1, cf: 3, jo: 'oval（楕円）＋glasses', eo: 'oval glasses', ev: '', sub: 'アイウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'オーバルサングラス', en: 'Oval Sunglasses', sp: 1, cf: 3, jo: 'oval＋sunglasses', eo: 'oval sunglasses', ev: '', sub: 'アイウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'スポーツサングラス', en: 'Sporty Sunglasses', sp: 1, cf: 3, jo: 'sports＋sunglasses', eo: 'sporty sunglasses', ev: '', sub: 'アイウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'バタフライサングラス', en: 'Cat-Eye Sunglasses', sp: 1, cf: 3, jo: 'butterfly（蝶の羽の形）', eo: 'cat-eye（猫の目の形）', ev: '日本語は蝶、英語は猫と、別の生き物にたとえている。', sub: 'アイウェア', t: ['clothes'] },
  { c: 'fashion', ja: 'ピカチュウカバー', en: 'Pikachu Case', sp: 1, cf: 3, jo: 'ピカチュウ＋cover', eo: 'Pikachu＋case', ev: 'スマホロトムのカバー。日本語は「カバー」、英語は「ケース」。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'イーブイカバー', en: 'Eevee Case', sp: 1, cf: 3, jo: 'イーブイ＋cover', eo: 'Eevee＋case', ev: '', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ニャオハカバー', en: 'Sprigatito Case', sp: 1, cf: 3, jo: 'ニャオハ＋cover', eo: 'Sprigatito＋case', ev: '', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ホゲータカバー', en: 'Fuecoco Case', sp: 1, cf: 3, jo: 'ホゲータ＋cover', eo: 'Fuecoco＋case', ev: '', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'クワッスカバー', en: 'Quaxly Case', sp: 1, cf: 3, jo: 'クワッス＋cover', eo: 'Quaxly＋case', ev: '', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'デフォルトカラー', en: 'Default Case', sp: 0, cf: 3, jo: 'default（初期設定の）＋color', eo: 'default＋case', ev: '最初のスマホロトムの色。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'イエローカラー', en: 'Yellow Case', sp: 1, cf: 3, jo: 'イエロー＋color（色）', eo: 'yellow＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'グリーンカラー', en: 'Green Case', sp: 1, cf: 3, jo: 'グリーン＋color（色）', eo: 'green＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'パープルカラー', en: 'Purple Case', sp: 1, cf: 3, jo: 'パープル＋color（色）', eo: 'purple＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ピンクカラー', en: 'Pink Case', sp: 1, cf: 3, jo: 'ピンク＋color（色）', eo: 'pink＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ブルーカラー', en: 'Blue Case', sp: 1, cf: 3, jo: 'ブルー＋color（色）', eo: 'blue＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'アクアグリーンカラー', en: 'Turquoise Case', sp: 1, cf: 3, jo: 'aqua green（アクアグリーン）＋color', eo: 'turquoise（トルコ石の青緑）＋case', ev: '同じ色を日本語はアクアグリーン、英語はターコイズと呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'オリーブカラー', en: 'Olive Case', sp: 1, cf: 3, jo: 'オリーブ＋color（色）', eo: 'olive＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ローズピンクカラー', en: 'Rose Case', sp: 1, cf: 3, jo: 'rose pink＋color', eo: 'rose＋case', ev: '', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ブラウンカラー', en: 'Brown Case', sp: 1, cf: 3, jo: 'ブラウン＋color（色）', eo: 'brown＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ラベンダーカラー', en: 'Lavender Case', sp: 1, cf: 3, jo: 'ラベンダー＋color（色）', eo: 'lavender＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'クリームカラー', en: 'Cream Case', sp: 1, cf: 3, jo: 'クリーム＋color（色）', eo: 'cream＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ダークグリーンカラー', en: 'Dark Green Case', sp: 1, cf: 3, jo: 'ダークグリーン＋color（色）', eo: 'dark green＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ワインレッドカラー', en: 'Wine Red Case', sp: 1, cf: 3, jo: 'ワインレッド＋color（色）', eo: 'wine red＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'オレンジカラー', en: 'Orange Case', sp: 1, cf: 3, jo: 'オレンジ＋color（色）', eo: 'orange＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'スカイブルーカラー', en: 'Sky Blue Case', sp: 1, cf: 3, jo: 'スカイブルー＋color（色）', eo: 'sky blue＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ネイビーブルーカラー', en: 'Navy Blue Case', sp: 1, cf: 3, jo: 'ネイビーブルー＋color（色）', eo: 'navy blue＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ココアブラウンカラー', en: 'Cocoa Brown Case', sp: 1, cf: 3, jo: 'ココアブラウン＋color（色）', eo: 'cocoa brown＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ダークブラウンカラー', en: 'Dark Brown Case', sp: 1, cf: 3, jo: 'ダークブラウン＋color（色）', eo: 'dark brown＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ホワイトカラー', en: 'White Case', sp: 1, cf: 3, jo: 'ホワイト＋color（色）', eo: 'white＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ブラックカラー', en: 'Black Case', sp: 1, cf: 3, jo: 'ブラック＋color（色）', eo: 'black＋case', ev: 'スマホロトムの色。日本語は「〜カラー」、英語は「〜ケース」と呼んでいる。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'くさカバー', en: 'Grass Case', sp: 1, cf: 3, jo: 'くさ（タイプ名）＋cover', eo: 'Grass（タイプ名）＋case', ev: 'くさタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'みずカバー', en: 'Water Case', sp: 1, cf: 3, jo: 'みず（タイプ名）＋cover', eo: 'Water（タイプ名）＋case', ev: 'みずタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ほのおカバー', en: 'Fire Case', sp: 1, cf: 3, jo: 'ほのお（タイプ名）＋cover', eo: 'Fire（タイプ名）＋case', ev: 'ほのおタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'でんきカバー', en: 'Electric Case', sp: 1, cf: 3, jo: 'でんき（タイプ名）＋cover', eo: 'Electric（タイプ名）＋case', ev: 'でんきタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ノーマルカバー', en: 'Normal Case', sp: 1, cf: 3, jo: 'ノーマル（タイプ名）＋cover', eo: 'Normal（タイプ名）＋case', ev: 'ノーマルタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ひこうカバー', en: 'Flying Case', sp: 1, cf: 3, jo: 'ひこう（タイプ名）＋cover', eo: 'Flying（タイプ名）＋case', ev: 'ひこうタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'むしカバー', en: 'Bug Case', sp: 1, cf: 3, jo: 'むし（タイプ名）＋cover', eo: 'Bug（タイプ名）＋case', ev: 'むしタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'かくとうカバー', en: 'Fighting Case', sp: 1, cf: 3, jo: 'かくとう（タイプ名）＋cover', eo: 'Fighting（タイプ名）＋case', ev: 'かくとうタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'エスパーカバー', en: 'Psychic Case', sp: 1, cf: 3, jo: 'エスパー（タイプ名）＋cover', eo: 'Psychic（タイプ名）＋case', ev: 'エスパータイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ゴーストカバー', en: 'Ghost Case', sp: 1, cf: 3, jo: 'ゴースト（タイプ名）＋cover', eo: 'Ghost（タイプ名）＋case', ev: 'ゴーストタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'じめんカバー', en: 'Ground Case', sp: 1, cf: 3, jo: 'じめん（タイプ名）＋cover', eo: 'Ground（タイプ名）＋case', ev: 'じめんタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'いわカバー', en: 'Rock Case', sp: 1, cf: 3, jo: 'いわ（タイプ名）＋cover', eo: 'Rock（タイプ名）＋case', ev: 'いわタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'こおりカバー', en: 'Ice Case', sp: 1, cf: 3, jo: 'こおり（タイプ名）＋cover', eo: 'Ice（タイプ名）＋case', ev: 'こおりタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'あくカバー', en: 'Dark Case', sp: 1, cf: 3, jo: 'あく（タイプ名）＋cover', eo: 'Dark（タイプ名）＋case', ev: 'あくタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'フェアリーカバー', en: 'Fairy Case', sp: 1, cf: 3, jo: 'フェアリー（タイプ名）＋cover', eo: 'Fairy（タイプ名）＋case', ev: 'フェアリータイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'どくカバー', en: 'Poison Case', sp: 1, cf: 3, jo: 'どく（タイプ名）＋cover', eo: 'Poison（タイプ名）＋case', ev: 'どくタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'はがねカバー', en: 'Steel Case', sp: 1, cf: 3, jo: 'はがね（タイプ名）＋cover', eo: 'Steel（タイプ名）＋case', ev: 'はがねタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ドラゴンカバー', en: 'Dragon Case', sp: 1, cf: 3, jo: 'ドラゴン（タイプ名）＋cover', eo: 'Dragon（タイプ名）＋case', ev: 'ドラゴンタイプの模様のスマホロトムのカバー。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'だきまるたカバー', en: 'Komala Log Case', sp: 1, cf: 3, jo: '抱き丸太（ネッコアラが抱えている丸太）', eo: 'Komala＋log', ev: '', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'はながらカバー', en: 'Flabébé Flower Case', sp: 1, cf: 3, jo: '花柄＋cover', eo: 'Flabébé＋flower＋case', ev: 'フラベベの花の柄。日本語はポケモン名を出さず「花柄」。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'じしゃくカバー', en: 'Magnemite Magnet Case', sp: 1, cf: 3, jo: '磁石＋cover', eo: 'Magnemite＋magnet＋case', ev: 'コイルの磁石の柄。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'リボンがらカバー', en: 'Gothita Ribbon Case', sp: 1, cf: 3, jo: 'リボン柄＋cover', eo: 'Gothita＋ribbon＋case', ev: 'ゴチムのリボンの柄。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'あおぞらカバー', en: 'Swablu Sky Case', sp: 1, cf: 3, jo: '青空＋cover', eo: 'Swablu＋sky＋case', ev: 'チルットと青空の柄。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'ハニーカバー', en: 'Combee Honey Case', sp: 1, cf: 3, jo: 'honey＋cover', eo: 'Combee＋honey＋case', ev: 'ミツハニーの蜂蜜の柄。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'リンゴカバー', en: 'Applin Apple Case', sp: 1, cf: 3, jo: 'リンゴ＋cover', eo: 'Applin＋apple＋case', ev: 'カジッチュのリンゴの柄。', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'スカーレットカバー', en: 'Scarlet Case', sp: 1, cf: 3, jo: 'スカーレット＋cover', eo: 'Scarlet＋case', ev: '', sub: 'スマホロトムのカバー', t: ['clothes'] },
  { c: 'fashion', ja: 'バイオレットカバー', en: 'Violet Case', sp: 1, cf: 3, jo: 'バイオレット＋cover', eo: 'Violet＋case', ev: '', sub: 'スマホロトムのカバー', t: ['clothes'] }
];

if (typeof module !== 'undefined') module.exports = FASHION_ENTRIES;
