/*
 * ポケモンSV元ネタ推測図鑑 ― 暮らしの名前（お店・料理・ピクニック・ファッション・地名の追加分）
 *
 * [カテゴリ, 日本語名, 英語名, ネタバレ段階, 確からしさ, 日本語名の由来, 英語名の由来, 補足（任意）, タグ（任意）]
 * 由来は文字列か、諸説あるときは配列（先頭が本命）。
 * カテゴリ：shop（お店）／food（料理・ピクニック）／fashion（ファッション）／place（地名）／person（人物）／term（用語）
 */
var LIFE_ENTRIES = [
  // ===== お店 =====
  ['shop', 'まいど・さんど', 'Every Wich Way', 0, 3, ['「まいど」（毎度ありがとう）＋サンド', '「まいど（毎度）・さんど（三度）」の言葉遊び。一度でも二度でも来てほしい、という店の呼びかけとも合う'], ['every which way（あらゆる方向に、めちゃくちゃに）', 'sandwich の「wich」と which の掛け言葉'], 'サンドウィッチの専門店。', ['chain']],
  ['shop', 'あまいやつめたいや', 'Sugar-N-Ice', 0, 3, '「甘いやつ（奴）・冷たいや」。あまい・つめたい・や（屋）がつながった言葉遊び', ['sugar and ice。童謡の一節「sugar and spice and everything nice」のもじり', 'nice（すてき）と ice の掛け言葉'], 'アイスクリームの屋台。', ['chain']],
  ['shop', '喫茶室なぎさ', 'Seabreeze Café', 0, 3, ['渚（なぎさ＝波打ち際）。昔ながらの喫茶店らしい名前', '「喫茶室」＝レトロな純喫茶の呼び方'], 'seabreeze（海風）＋café', 'カフェ。日英とも「海辺」のイメージ。', ['chain']],
  ['shop', 'レストラン 鮮度一番!', 'Seafood Fresco', 1, 3, '鮮度（新鮮さ）が一番！', ['seafood（海鮮）＋fresco（スペイン語・イタリア語で「新鮮な」）', 'al fresco（屋外で）の響き'], '海鮮料理のレストラン。', ['chain']],
  ['shop', 'ファミリーレストラン バラト', "Barato's", 1, 3, 'barato（スペイン語・ポルトガル語で「安い」）', "barato（安い）＋'s（〜の店）", 'ファミリーレストラン。日英とも「安い」。', ['chain']],
  ['shop', 'バル・キバル', 'Go-For-Broke Grill', 1, 3, ['bar（バル＝スペインの立ち飲み居酒屋）＋気張る（きばる＝奮発する）', '「バル」と「キバル」の韻'], 'go for broke（一か八か全力を出す、有り金をはたく）＋grill', 'パエリアなどスペイン料理の店。日英とも「奮発する」の意味になっている。', ['chain']],
  ['shop', '宝食堂', 'Treasure Eatery', 1, 3, ['宝（たから）＋食堂', '課外授業「宝探し」とも掛かる'], 'treasure（宝）＋eatery（食堂）', 'チャンプルタウンの食堂。居酒屋風の店で、奥の座敷がジムのバトルコートになる。'],
  ['shop', 'ガストロノミー ファミリア', 'Gastronomie en Famille', 1, 3, 'gastronomie（フランス語で美食）＋familia（スペイン語で家族）', 'gastronomie en famille（フランス語で「家族で楽しむ美食」）', '高級フランス料理店。料理の名前に家族を表す言葉（ママン・パピィ・マミー・フィス・フィー）が入っている。', ['chain']],
  ['shop', 'カントークレープ', 'Kanto Crepes', 1, 3, ['カントー地方（初代の舞台）＋クレープ', '関東（原宿のクレープ）の掛け言葉'], 'Kanto＋crepes', 'クレープの屋台。', ['chain']],
  ['shop', '串のトリコ', 'Chic Kebab', 1, 3, ['串（くし）＋虜（とりこ＝夢中）', '「とりこ」に鳥（とり）を掛けた言葉遊び'], ['chic（おしゃれ）＋kebab（串焼き）', 'chick（ひよこ・鶏）の語呂'], '串焼きの屋台。', ['chain']],
  ['shop', 'チュロスにチュ!', 'Smoochurro', 1, 3, 'チュロス＋チュッ（キスの音）', 'smooch（キス）＋churro', 'チュロスの屋台。日英とも「キス」の言葉遊び。', ['chain']],
  ['shop', '来来来軒', 'Jade Palace Garden', 1, 3, ['日本の町中華によくある店名「来来軒」をさらに重ねた名前', '「来（らい）」＝また来てね'], 'jade（翡翠）＋palace（宮殿）＋garden。中華料理店らしい名前', '中華料理店。'],
  ['shop', 'ローリングドリーマー', 'Sushi High Roller', 1, 3, ['rolling（回転）＋dreamer。回転寿司', 'rolling＝寿司の巻き（ロール）'], ['sushi＋high roller（大金を賭ける人）', 'roller＝回転寿司の回転'], '回転寿司の店。'],
  ['shop', 'ハイダイ倶楽部', 'Kofu Lounge', 1, 3, 'ハイダイ（ジムリーダー）＋倶楽部（クラブ）', 'Kofu（ハイダイの英語名）＋lounge', 'カラフシティのジムリーダー、ハイダイが営む中華料理店。'],
  ['shop', '缶の大将', 'Sure Cans', 0, 3, '缶（かん）＋大将（店主の呼び名）', ['sure can（もちろんできるよ）', 'cans（缶詰）'], 'サンドウィッチの材料の店。'],
  ['shop', 'オーラオーラ', 'Deli Cioso', 0, 3, ['hola（スペイン語で「やあ」）＋olla（スペイン語で鍋）', '「オーラ、オーラ」＝陽気なあいさつの繰り返し'], ['deli（デリカテッセン、総菜店）＋delicioso（スペイン語で「おいしい」）'], 'サンドウィッチの材料の店。'],
  ['shop', 'ベーカリー オルノ', 'Artisan Bakery', 0, 3, 'horno（スペイン語でかまど・オーブン）', 'artisan（職人の）＋bakery', 'パンと調味料の店。'],
  ['shop', 'スーパー アルデネーノ', 'Aquiesta Supermarket', 1, 2, ['aldeano（スペイン語で村人）の響き', 'aldea（村）'], 'aquí está（スペイン語で「ここにあるよ」）', 'ハッコウシティのスーパーマーケット。'],
  ['shop', 'デリバードポーチ', 'Delibird Presents', 0, 3, 'デリバード＋pouch（袋）。プレゼント袋を持つデリバードから', 'Delibird＋presents（贈り物／提供する）', '持ち物・ボールなどを売る店。'],
  ['shop', 'ラッキーズ', 'Chansey Supply', 0, 3, ['ラッキー（ポケモン）＋「〜ズ」（店名の’s）', 'ドラッグストアの店名風'], 'Chansey（ラッキーの英語名）＋supply（供給）', '薬の店。ラッキーは看護のイメージのポケモン。'],
  ['shop', 'フレンドリィショップ', 'Poké Mart', 0, 3, 'friendly（親しみやすい）＋shop', 'Poké＋mart（市場・店）', 'ポケモンセンターの中にある店。シリーズ伝統の名前。'],
  ['shop', 'NOHARA', 'Picnic-Knacks', 1, 3, '野原（のはら）', ['picnic＋knick-knacks（小物・雑貨）'], 'ピクニック用品の店。'],
  ['shop', 'CEOOU', "Bagin's", 1, 3, '背負う（せおう）', ["bag（かばん）＋-in's", '『指輪物語』のバギンズ（Baggins）の語呂'], 'リュックの店。', ['fashion']],
  ['shop', 'R&T', 'Rough & Tough', 1, 3, 'rough & tough（荒っぽくて丈夫）の頭文字', 'rough & tough', 'アウトドア服の店。', ['fashion']],
  ['shop', 'キャ・ブール', 'Capbourg', 1, 3, ['cap（帽子）＋bourg（フランス語で町）', 'キャップ＋「ブール」（フランス風の響き）'], 'cap＋-bourg（シェルブールなどフランスの地名風）', '帽子の店。', ['fashion']],
  ['shop', 'メガネの里', 'Spec Shack', 1, 3, ['メガネ＋里（さと）。眼鏡の産地の雰囲気', '「〜の里」は老舗風の店名の定番'], 'specs（眼鏡）＋shack（小屋）。頭韻を踏む', '眼鏡の店。', ['fashion']],
  ['shop', 'あしのとも', 'Sock Quarter', 1, 3, '足の友', ['sock（靴下）＋quarter（地区・4分の1）', 'sock と quarter の音の響き'], '靴下・タイツの店。', ['fashion']],
  ['shop', 'パルデア靴センター', 'Zapaldea Footwear', 1, 3, 'パルデア＋靴センター', 'zapato（スペイン語で靴）＋Paldea', '靴の店。', ['fashion']],
  ['shop', 'ヘアメイクサロン リボーン', 'Salon Renacer', 1, 3, 'reborn（生まれ変わる）', 'renacer（スペイン語で生まれ変わる）', '美容室。日英とも「生まれ変わる」。', ['fashion']],
  ['shop', 'セグーロ', 'Seguro Style', 1, 3, 'seguro（スペイン語で安全）', 'seguro＋style', 'ヘルメットとグローブの店。安全装備にぴったりの名前。', ['fashion']],
  ['shop', 'ベルダー', 'Veracidad', 1, 3, 'verdad（スペイン語で真実）', 'veracidad（スペイン語で真実性）', '「ワンランク上のオシャレ」をうたう高級服の店。日英とも「真実」を表す言葉。', ['fashion']],
  ['shop', 'マリナード市場', 'Porto Marinada Market', 1, 3, 'マリナード（町の名前）＋市場', 'Porto Marinada＋market', '競り（オークション）が行われる市場。'],

  // ===== 料理（お店のメニュー） =====
  ['food', 'チョコミントアイス', 'Mint Chocolate Ice Cream', 0, 3, 'chocolate＋mint＋ice', 'mint chocolate ice cream', 'あまいやつめたいやのメニュー。', ['menu']],
  ['food', 'ソーダアイス', 'Fizzy Ice Cream', 0, 3, 'soda＋ice', 'fizzy（しゅわしゅわした）', 'あまいやつめたいやのメニュー。', ['menu']],
  ['food', 'コジオソルトアイス', 'Nacli Salt Ice Cream', 0, 3, 'コジオ（岩塩のポケモン）＋salt＋ice', 'Nacli（コジオの英語名）＋salt ice cream', '塩のポケモンの名前が入ったアイス。', ['menu']],
  ['food', 'TERIYAKIアイス', 'Teriyaki Ice Cream', 1, 3, '照り焼き（テリヤキ）＋アイス。ローマ字表記で「外国で人気の和食」の雰囲気', 'teriyaki ice cream', 'あまいやつめたいやのメニュー。', ['menu']],
  ['food', 'アルファホール', 'Alfajores', 1, 3, 'alfajor（スペインや南米の焼き菓子アルファホール）', 'alfajores（alfajor の複数形）', '喫茶室なぎさのメニュー。', ['menu']],
  ['food', 'ケサディーヤ', 'Quesadilla', 1, 3, 'quesadilla（メキシコ料理、queso＝チーズから）', 'quesadilla', '喫茶室なぎさのメニュー。', ['menu']],
  ['food', 'スパイシーポテト', 'Spicy Potatoes', 1, 2, 'spicy potato。スペインのバルの定番「パタタス・ブラバス」がモデルとみられる', 'spicy potatoes', '喫茶室なぎさのメニュー。', ['menu']],
  ['food', '海の幸のピンチョス', 'Seafood Pinchos', 1, 3, 'pincho（スペイン語で串・小さなつまみ）', 'seafood＋pinchos', 'レストラン 鮮度一番!のメニュー。', ['menu']],
  ['food', 'アロス・コン・レチェ', 'Arroz con Leche', 1, 3, 'arroz con leche（スペイン語で「牛乳入りの米」、お米のデザート）', 'arroz con leche', 'レストラン 鮮度一番!のメニュー。', ['menu']],
  ['food', 'セビーチェ', 'Ceviche', 1, 3, 'ceviche（魚介のマリネ、中南米の料理）', 'ceviche', 'レストラン 鮮度一番!のメニュー。', ['menu']],
  ['food', 'ドライカレー', 'Dry Curry', 1, 3, 'dry curry（日本の洋食で生まれた汁気の少ないカレー）', 'dry curry', 'ファミリーレストラン バラトのメニュー。', ['menu']],
  ['food', 'ハンバーグ&ミックスフライ', 'Salisbury Steak with Fried Fixings', 1, 3, '日本の洋食の定番の組み合わせ', 'Salisbury steak（ハンバーグに近いアメリカの料理）＋fixings（付け合わせ）', '日本語の「ハンバーグ」は英語ではハンバーガーと紛らわしいため、Salisbury steak と訳されている。', ['menu']],
  ['food', 'パエジャ＝パルデア', 'Paella de Paldea', 1, 3, ['paella（パエリア）をスペイン語の発音に近く「パエジャ」と書いたもの＋パルデア', 'パエリアとパルデアの響きが近いことを生かした名前'], 'paella de Paldea（パルデアのパエリア）', 'バル・キバルのメニュー。パルデアという地方名とパエリアの響きの近さも楽しめる。', ['menu']],
  ['food', 'エスカリバダ', 'Escalivada', 1, 3, 'escalivada（カタルーニャの焼き野菜料理）', 'escalivada', 'バル・キバルのメニュー。', ['menu']],
  ['food', 'トルティージャ', 'Potato Tortilla', 0, 3, 'tortilla（スペインのじゃがいも入りオムレツ）', 'potato＋tortilla', 'バル・キバルのメニュー。サンドウィッチの材料にもある。', ['menu', 'ing']],
  ['food', 'ガケガニ・アル・アヒージョ', 'Klawf al Ajillo', 1, 3, 'ガケガニ（ポケモン）＋al ajillo（スペイン語で「にんにく風味の」、アヒージョ）', 'Klawf＋al ajillo', 'ポケモンの名前がそのまま料理名になっている。', ['menu']],
  ['food', 'からしむすび', 'Mustard Rice Ball', 1, 3, 'からし＋おむすび', 'mustard＋rice ball', '宝食堂のメニュー。', ['menu']],
  ['food', 'ぜんざい', 'Sweet Adzuki Bean Soup', 1, 3, 'ぜんざい（善哉）', 'sweet adzuki bean soup（説明的な訳）', '宝食堂のメニュー。', ['menu']],
  ['food', '自家製うめぼし', 'Homemade Umeboshi', 1, 3, '自家製＋梅干し', 'homemade＋umeboshi', '宝食堂のメニュー。', ['menu']],
  ['food', 'ゴーヤーチャンプル', 'Bitter Melon Stir-Fry', 1, 3, 'ゴーヤー＋チャンプルー（沖縄の混ぜ炒め）', 'bitter melon（ゴーヤー）＋stir-fry（炒め物）', 'チャンプルタウン（名前の由来も「チャンプルー」）の宝食堂のメニュー。', ['menu']],
  ['food', 'かけそば', 'Soba Noodle Soup', 1, 3, 'かけ（汁をかける）＋そば', 'soba noodle soup', '宝食堂のメニュー。', ['menu']],
  ['food', 'ママンのガレット', 'Galette de la Maman', 1, 3, 'maman（フランス語でママ）＋galette（そば粉のクレープ）', 'galette de la maman（ママのガレット）', 'ガストロノミー ファミリアの「家族」シリーズ。', ['menu']],
  ['food', 'フィスのコンポート', 'Compote du Fils', 1, 3, 'fils（フランス語で息子）＋compote（果物の甘煮）', 'compote du fils（息子のコンポート）', 'ガストロノミー ファミリアの「家族」シリーズ。', ['menu']],
  ['food', 'パピィのラタトゥイユ', 'Ratatouille du Grand-père', 1, 3, 'papi（フランス語でおじいちゃん）＋ratatouille', 'ratatouille du grand-père（おじいさんのラタトゥイユ）', 'ガストロノミー ファミリアの「家族」シリーズ。', ['menu']],
  ['food', 'マミーのキッシュ', 'Quiche de la Grand-mère', 1, 3, 'mamie（フランス語でおばあちゃん）＋quiche', 'quiche de la grand-mère（おばあさんのキッシュ）', 'ガストロノミー ファミリアの「家族」シリーズ。', ['menu']],
  ['food', 'フィーのポトフ', 'Pot-au-Feu de la Fille', 1, 3, 'fille（フランス語で娘）＋pot-au-feu', 'pot-au-feu de la fille（娘のポトフ）', 'ガストロノミー ファミリアの「家族」シリーズ。', ['menu']],
  ['food', 'いちごチョコクレープ', 'Strawberry Chocolate Crepe', 1, 3, 'いちご＋チョコ＋クレープ', 'strawberry chocolate crepe', 'カントークレープのメニュー。', ['menu']],
  ['food', 'チョコバナナクレープ', 'Chocolate Banana Crepe', 1, 3, 'チョコ＋バナナ＋クレープ', 'chocolate banana crepe', 'カントークレープのメニュー。', ['menu']],
  ['food', 'ピンチョ・モルノ', 'Pinchitos', 1, 3, 'pincho moruno（スペイン語で「ムーア風の串焼き」）', 'pinchitos（小さな串、pincho の縮小形）', '串のトリコのメニュー。', ['menu']],
  ['food', '焼きおにぎり', 'Grilled Rice Balls', 1, 3, '焼き＋おにぎり', 'grilled rice balls', '串のトリコのメニュー。', ['menu']],
  ['food', 'チュロス', 'Churro', 1, 3, 'churro（スペインの揚げ菓子）', 'churro', 'チュロスにチュ!のメニュー。', ['menu']],
  ['food', '麻婆豆腐', 'Mapo Tofu', 1, 3, '麻婆豆腐（あばた顔のおばあさんが考えたという言い伝えのある四川料理）', 'mapo tofu', '来来来軒のメニュー。', ['menu']],
  ['food', '杏仁豆腐', 'Annin Tofu', 1, 3, '杏仁（あんずの種）＋豆腐（形が似ている）', 'annin tofu（日本語読みのまま）', '来来来軒のメニュー。', ['menu']],
  ['food', '青椒肉絲', 'Pepper Steak', 1, 3, '青椒（ピーマン）＋肉絲（細切り肉）', 'pepper steak（アメリカの中華料理の呼び名）', '来来来軒のメニュー。', ['menu']],
  ['food', '4カンセット 〜花〜〜月〜', 'Four-Piece Sushi (Flower–Moon)', 1, 3, '4貫（かん）セット。「花・鳥・風・月」の4種類で、四字熟語「花鳥風月」になる', 'four-piece sushi（Flower/Bird/Wind/Moon Set）', 'ローリングドリーマーのメニュー。', ['menu']],
  ['food', '限定4カンセット 〜霜〜〜霙〜', 'Exclusive Four-Piece Sushi (Frost–Sleet)', 1, 3, '霜（しも）・霰（あられ）・雹（ひょう）・霙（みぞれ）の、空から降る冬のもの4種', 'Frost/Graupel/Hail/Sleet Set', '限定メニュー。雨かんむりの漢字がそろっている。', ['menu']],
  ['food', 'ダンダンミェン', 'Dandan Noodles', 1, 3, '担担麺（dàndànmiàn）の中国語読み', 'dandan noodles', 'ハイダイ倶楽部のメニュー。日本語名は中国語の発音に近い表記。', ['menu']],
  ['food', 'ドウファー', 'Tofu Pudding', 1, 3, '豆花（dòuhuā、中華の豆腐スイーツ）', 'tofu pudding', 'ハイダイ倶楽部のメニュー。', ['menu']],
  ['food', 'サンラータン', 'Hot and Sour Soup', 1, 3, '酸辣湯（suānlàtāng、酸っぱくて辛いスープ）', 'hot and sour soup', 'ハイダイ倶楽部のメニュー。', ['menu']],
  ['food', 'チンチャ', 'Oolong Tea', 1, 2, '清茶（qīngchá、澄んだお茶）の中国語読みとみられる', 'oolong tea', 'ハイダイ倶楽部のメニュー。', ['menu']],
  ['food', 'フォーティャオチァン', 'House Special Hot Pot', 1, 3, '佛跳牆（fótiàoqiáng＝「仏様も塀を飛び越えて食べに来る」ほどおいしいという高級スープ）', 'house special hot pot', 'ハイダイ倶楽部のメニュー。', ['menu']],

  ['food', 'ストロベリーアイス', 'Strawberry Ice Cream', 0, 3, 'strawberry＋ice', 'strawberry ice cream', 'あまいやつめたいやのメニュー。', ['menu']],
  ['food', 'マンゴーアイス', 'Mango Ice Cream', 0, 3, 'mango＋ice', 'mango ice cream', 'あまいやつめたいやのメニュー。', ['menu']],
  ['food', 'レモネード', 'Lemon Soda', 1, 3, 'lemonade（レモン果汁の飲み物）', 'lemon soda', '喫茶室なぎさのメニュー。日本語はレモネード、英語はレモンソーダ。', ['menu']],
  ['food', 'コーヒー', 'Coffee', 1, 3, 'koffie（オランダ語）から日本語に入った言葉', 'coffee', '喫茶室なぎさのメニュー。', ['menu']],
  ['food', 'スモークきりみのハーブ添え', 'Smoked Fillet with Herbs', 1, 3, '燻製の切り身＋ハーブ添え', 'smoked fillet with herbs', 'レストラン 鮮度一番!のメニュー。', ['menu']],
  ['food', 'シーフードパスタ', 'Seafood Pasta', 1, 3, 'seafood＋pasta', 'seafood pasta', 'レストラン 鮮度一番!のメニュー。', ['menu']],
  ['food', 'チョコバニラフルーツパフェ', 'Chocolate-Vanilla Fruit Parfait', 1, 3, 'chocolate＋vanilla＋fruit＋parfait（フランス語で「完全な」）', 'chocolate-vanilla fruit parfait', 'ファミリーレストラン バラトのメニュー。', ['menu']],
  ['food', 'レモンのジェラート', 'Lemon Gelato', 1, 3, 'lemon＋gelato（イタリア語で「凍った」、アイス）', 'lemon gelato', 'ファミリーレストラン バラトのメニュー。', ['menu']],
  ['food', 'シーザーサラダ', 'Caesar Salad', 1, 3, 'Caesar salad（考案したレストラン店主シーザー・カルディーニの名から）', 'caesar salad', 'ファミリーレストラン バラトのメニュー。', ['menu']],
  ['food', 'フルーツミックスジュース', 'Fruit Punch', 1, 3, 'fruit＋mix＋juice', 'fruit punch', 'バル・キバルのメニュー。英語の punch はインドの「5つの材料」を意味する言葉から、という説がある。', ['menu']],
  ['food', 'いちごホイップクレープ', 'Strawberry Whipped Cream Crepe', 1, 3, 'いちご＋whip＋crepe', 'strawberry whipped cream crepe', 'カントークレープのメニュー。', ['menu']],
  ['food', 'チョコチュロス', 'Chocolate Churro', 1, 3, 'chocolate＋churro', 'chocolate churro', 'チュロスにチュ!のメニュー。', ['menu']],
  ['food', 'シナモンチュロス', 'Cinnamon Churro', 1, 3, 'cinnamon＋churro', 'cinnamon churro', 'チュロスにチュ!のメニュー。', ['menu']],
  ['food', 'ノノクラゲとキュウリの酢の物', 'Pickled Toedscool and Cucumber', 1, 3, ['ノノクラゲ（キノコのようなクラゲのポケモン）＋キュウリ＋酢の物。中華料理の前菜「クラゲの酢の物（海蜇）」がモデルとみられる'], 'pickled（酢漬けの）＋Toedscool（ノノクラゲの英語名）＋cucumber', '来来来軒のメニュー。ポケモンの名前が入った料理だが、本物のクラゲの前菜を下敷きにしている。', ['menu']],
  ['food', 'ラーメン', 'Ramen', 1, 3, 'ラーメン（拉麺）', 'ramen', '来来来軒のメニュー。', ['menu']],
  ['food', 'ミソスープ', 'Miso Soup', 1, 3, '味噌汁をカタカナで「ミソスープ」と書いた、外国風の呼び方', 'miso soup', 'ローリングドリーマーのメニュー。', ['menu']],
  ['food', 'クリアスープ', 'Consommé', 1, 3, 'clear soup（澄んだスープ）', 'consommé', 'ローリングドリーマーのメニュー。英語はフランス語の consommé（コンソメ）。', ['menu']],

  // ===== サンドウィッチのレシピ =====
  ['food', 'ジャンボンブール', 'Jambon-Beurre', 0, 3, 'jambon-beurre（フランス語で「ハム・バター」、パリの定番サンド）', 'jambon-beurre', '最初から作れるレシピ。「にがみの〜」など秘伝スパイス入りの版もある。', ['sand']],
  ['food', 'レジェンド〇〇サンド', 'Legendary 〇〇 Sandwich', 1, 3, 'legend（伝説）＋味（にがみ・しおみ・あまみ・さんみ・からみ）＋サンド', 'legendary＋味（Bitter / Salty / Sweet / Sour / Spicy）＋sandwich', '秘伝スパイスを使うレシピ。レジェンドルートの物語と関わる。', ['sand']],
  ['food', 'ジャムサンド', 'Jam Sandwich', 0, 3, 'jam＋サンド', 'jam sandwich', 'レシピには「スーパー」「ハイパー」「マスター」の上位版がある。', ['sand']],
  ['food', 'ピーナッツバターサンド', 'Peanut Butter Sandwich', 1, 3, 'peanut butter＋サンド。バナナと合わせるアメリカの定番', 'peanut butter sandwich', '', ['sand']],
  ['food', 'ピクルスサンド', 'Pickle Sandwich', 0, 3, 'pickles＋サンド', 'pickle sandwich', '', ['sand']],
  ['food', 'マーマレードサンド', 'Marmalade Sandwich', 1, 3, 'marmalade＋サンド', 'marmalade sandwich。イギリスのくまのキャラクターの好物としても有名', '', ['sand']],
  ['food', 'ハーブソーセージサンド', 'Herbed-Sausage Sandwich', 1, 3, 'herb sausage＋サンド', 'herbed sausage sandwich', '', ['sand']],
  ['food', 'カレーライスふうサンド', 'Curry-and-Rice-Style Sandwich', 1, 3, 'カレーライス風のサンド', 'curry-and-rice-style', '', ['sand']],
  ['food', 'おやつサンド', 'Dessert Sandwich', 1, 3, 'おやつ（間食）＋サンド', 'dessert sandwich', '', ['sand']],
  ['food', 'トロピカルサンド', 'Tropical Sandwich', 1, 3, 'tropical（熱帯の）＋サンド', 'tropical sandwich', '', ['sand']],
  ['food', 'アボカドサンド', 'Avocado Sandwich', 1, 3, 'avocado＋サンド', 'avocado sandwich', '', ['sand']],
  ['food', 'ヌードルサンド', 'Noodle Sandwich', 1, 3, 'noodle＋サンド。焼きそばパンの雰囲気', 'noodle sandwich', '', ['sand']],
  ['food', 'ポテトサラダサンド', 'Potato Salad Sandwich', 1, 3, 'potato salad＋サンド', 'potato salad sandwich', '', ['sand']],
  ['food', 'スパイシーサンド', 'Zesty Sandwich', 1, 3, 'spicy（辛い）＋サンド', 'zesty（ぴりっとした、風味の強い）', '', ['sand']],
  ['food', 'たまごサンド', 'Egg Sandwich', 1, 3, '卵＋サンド', 'egg sandwich', '', ['sand']],
  ['food', 'きほんのサンド', 'Classic Bocadillo', 1, 3, '基本の＋サンド', 'classic＋bocadillo（スペイン語でバゲットのサンドウィッチ）', '生ハムとトルティージャを挟んだスペイン風。英語版はスペイン語で呼んでいる。', ['sand']],
  ['food', 'さわやかサンド', 'Refreshing Sandwich', 1, 3, '爽やか＋サンド', 'refreshing（さわやかな）', '', ['sand']],
  ['food', 'BLTサンド', 'BLT Sandwich', 1, 3, 'B（ベーコン）・L（レタス）・T（トマト）', 'BLT（bacon, lettuce, tomato）', '', ['sand']],
  ['food', 'きりみフライサンド', 'Fried Fillet Sandwich', 1, 3, '切り身＋フライ＋サンド', 'fried fillet sandwich', '', ['sand']],
  ['food', 'ハムサンド', 'Ham Sandwich', 0, 3, 'ham＋サンド', 'ham sandwich', '', ['sand']],
  ['food', 'チーズサンド', 'Cheese Sandwich', 0, 3, 'cheese＋サンド', 'cheese sandwich', '', ['sand']],
  ['food', 'ハンバーグサンド', 'Hamburger Patty Sandwich', 1, 3, 'ハンバーグ＋サンド', 'hamburger patty（ハンバーグの肉）＋sandwich', '', ['sand']],
  ['food', 'スモークきりみサンド', 'Smoky Sandwich', 1, 3, 'smoke（燻製）＋切り身＋サンド', 'smoky（燻製の香りの）', '', ['sand']],
  ['food', 'フルーツサンド', 'Fruit Sandwich', 1, 3, 'fruit＋サンド。日本の喫茶店の定番', 'fruit sandwich', '', ['sand']],
  ['food', 'ミックスサンド', 'Variety Sandwich', 1, 3, 'mix（いろいろ）＋サンド', 'variety（いろいろな）', '', ['sand']],
  ['food', 'ガケガニサンド', 'Klawf Claw Sandwich', 1, 3, 'ガケガニ（ポケモン）＋サンド', 'Klawf＋claw（ハサミ）＋sandwich', '', ['sand']],
  ['food', 'スィートサンド', 'Sweet Sandwich', 1, 3, 'sweet（甘い）＋サンド', 'sweet sandwich', '', ['sand']],
  ['food', 'おやさいサンド', 'Vegetable Sandwich', 1, 3, 'お野菜＋サンド', 'vegetable sandwich', '家でママから教わるレシピ。', ['sand']],
  ['food', 'ボリュームサンド', 'Hefty Sandwich', 1, 3, 'volume（量が多い、の和製英語的な使い方）＋サンド', 'hefty（ずっしりした）', '', ['sand']],
  ['food', 'おとなのサンド', 'Five-Alarm Sandwich', 1, 3, '大人の（辛くて刺激的な）＋サンド', 'five-alarm（消防の出動規模から「激辛」の意味）', '日本語は「大人の味」、英語は「激辛」と、同じ辛さを別の言い回しで表している。', ['sand']],
  ['food', 'ネオやさいサンド', 'Nouveau Veggie Sandwich', 2, 3, 'neo（新しい）＋野菜＋サンド', 'nouveau（フランス語で新しい）＋veggie', '殿堂入り後に家でママから教わるレシピ。日英とも「新しい」。', ['sand']],
  ['food', 'あまからサンド', 'Spicy-Sweet Sandwich', 1, 3, '甘辛（あまから）＋サンド', 'spicy-sweet', '', ['sand']],
  ['food', 'リッチサンド', 'Decadent Sandwich', 1, 3, 'rich（ぜいたくな）＋サンド', 'decadent（退廃的なほどぜいたくな）', '', ['sand']],
  ['food', 'トーフサンド', 'Tofu Sandwich', 1, 3, 'tofu＋サンド', 'tofu sandwich', '', ['sand']],
  ['food', 'カレー&ヌードルサンド', 'Curry-and-Noodle Sandwich', 1, 3, 'カレー＋ヌードル＋サンド', 'curry-and-noodle', '', ['sand']],
  ['food', 'タワーサンド', 'Tower Sandwich', 1, 3, 'tower（塔）＋サンド。具を高く積み上げる', 'tower sandwich', '', ['sand']],
  ['food', 'スシふうサンド', 'Sushi Sandwich', 1, 3, '寿司風のサンド', 'sushi sandwich', 'オージャの湖にいる人から教わるレシピ。', ['sand']],

  // ===== サンドウィッチの材料 =====
  ['food', 'ガケガニスティック', 'Klawf Stick', 1, 3, ['ガケガニ（ポケモン）＋stick。カニかま（カニ風味かまぼこ）のもじり', 'crab stick（カニかまの英語）'], 'Klawf＋stick（crab stick のもじり）', 'ポケモンの名前がそのまま食材名になっている。', ['ing']],
  ['food', 'アーリーレッド', 'Red Onion', 0, 3, 'Early Red（赤玉ねぎの品種名）', 'red onion（赤玉ねぎ）', '日本語版は品種名、英語版は一般名になっている。', ['ing']],
  ['food', 'なまハム', 'Prosciutto', 0, 3, '生ハム', 'prosciutto（イタリア語で生ハム）', '', ['ing']],
  ['food', 'やきチョリソー', 'Chorizo', 1, 3, '焼き＋chorizo（スペインのソーセージ）', 'chorizo', '', ['ing']],
  ['food', 'スモークきりみ', 'Smoked Fillet', 1, 3, 'smoke（燻製）＋切り身', 'smoked fillet', '', ['ing']],
  ['food', 'スライスエッグ', 'Egg', 1, 3, 'slice＋egg', 'egg', '', ['ing']],
  ['food', 'わぎりリンゴ', 'Apple', 0, 3, '輪切り＋リンゴ', 'apple', '', ['ing']],
  ['food', 'カットパイン', 'Pineapple', 0, 3, 'cut＋pine（パイナップルの略）', 'pineapple', '', ['ing']],
  ['food', 'クレソン', 'Watercress', 1, 3, 'cresson（フランス語）', 'watercress', '', ['ing']],
  ['food', 'ハラペーニョ', 'Jalapeño', 1, 3, 'jalapeño（メキシコの唐辛子。ハラパという町の名前から）', 'jalapeño', '', ['ing']],
  ['food', 'ワサビソース', 'Wasabi', 1, 3, 'わさび＋ソース', 'wasabi', '', ['ing']],
  ['food', 'ホースラディッシュ', 'Horseradish', 1, 3, 'horseradish（西洋わさび）', 'horseradish', '歴史の先生レホールの名前（フランス語の raifort＝西洋わさび）ともつながる食材。', ['ing']],
  ['food', 'ベリージャム', 'Jam', 0, 3, 'berry＋jam', 'jam', '', ['ing']],
  ['food', 'ピーナッツバター', 'Peanut Butter', 1, 3, 'peanut butter', 'peanut butter', '', ['ing']],
  ['food', 'チリソース', 'Chili Sauce', 1, 3, 'chili（唐辛子）＋sauce', 'chili sauce', '四天王チリの名前とも同じ「チリ」。', ['ing']],
  ['food', 'カレーパウダー', 'Curry Powder', 1, 3, 'curry powder', 'curry powder', '', ['ing']],

  ['food', 'レタス', 'Lettuce', 0, 3, 'lettuce', 'lettuce', 'サンドウィッチの材料。', ['ing']],
  ['food', 'トマトスライス', 'Tomato', 0, 3, 'tomato＋slice', 'tomato', 'サンドウィッチの材料。', ['ing']],
  ['food', 'カットミニトマト', 'Cherry Tomatoes', 0, 3, 'cut＋mini tomato', 'cherry tomatoes', 'サンドウィッチの材料。', ['ing']],
  ['food', 'キュウリスライス', 'Cucumber', 0, 3, '胡瓜（きゅうり）＋slice', 'cucumber', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ピクルススライス', 'Pickle', 0, 3, 'pickles＋slice', 'pickle', 'サンドウィッチの材料。', ['ing']],
  ['food', 'たまねぎスライス', 'Onion', 0, 3, '玉ねぎ＋slice', 'onion', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ピーマンスライス', 'Green Bell Pepper', 0, 3, 'piment（フランス語で唐辛子）＋slice', 'green bell pepper', 'サンドウィッチの材料。', ['ing']],
  ['food', 'あかパプリカスライス', 'Red Bell Pepper', 0, 3, '赤＋paprika＋slice', 'red bell pepper', 'サンドウィッチの材料。', ['ing']],
  ['food', 'きパプリカスライス', 'Yellow Bell Pepper', 0, 3, '黄＋paprika＋slice', 'yellow bell pepper', 'サンドウィッチの材料。', ['ing']],
  ['food', 'アボカド', 'Avocado', 0, 3, 'avocado（ナワトル語の ahuacatl から）', 'avocado', 'サンドウィッチの材料。', ['ing']],
  ['food', 'やきベーコン', 'Bacon', 0, 3, '焼き＋bacon', 'bacon', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ハムスライス', 'Ham', 0, 3, 'ham＋slice', 'ham', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ハーブソーセージ', 'Herbed Sausage', 0, 3, 'herb＋sausage', 'herbed sausage', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ハンバーグ', 'Hamburger', 0, 3, 'Hamburg（ドイツの都市ハンブルク）風のステーキから', 'hamburger', 'サンドウィッチの材料。', ['ing']],
  ['food', 'きりみフライ', 'Fried Fillet', 0, 3, '切り身＋fry', 'fried fillet', 'サンドウィッチの材料。', ['ing']],
  ['food', 'トーフ', 'Tofu', 0, 3, '豆腐をカタカナで書いたもの', 'tofu', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ライス', 'Rice', 0, 3, 'rice。「ごはん」ではなく英語の呼び方', 'rice', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ヌードル', 'Noodles', 0, 3, 'noodle', 'noodles', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ポテトサラダ', 'Potato Salad', 0, 3, 'potato salad', 'potato salad', 'サンドウィッチの材料。', ['ing']],
  ['food', 'スライスチーズ', 'Cheese', 0, 3, 'slice＋cheese', 'cheese', 'サンドウィッチの材料。', ['ing']],
  ['food', 'バナナスライス', 'Banana', 0, 3, 'banana＋slice', 'banana', 'サンドウィッチの材料。', ['ing']],
  ['food', 'いちごスライス', 'Strawberry', 0, 3, '苺＋slice', 'strawberry', 'サンドウィッチの材料。', ['ing']],
  ['food', 'わぎりキウイ', 'Kiwi', 0, 3, '輪切り＋kiwi（ニュージーランドの鳥キーウィにちなむ果物名）', 'kiwi', 'サンドウィッチの材料。', ['ing']],
  ['food', 'バジル', 'Basil', 0, 3, 'basil', 'basil', 'サンドウィッチの材料。', ['ing']],
  ['food', 'マヨネーズ', 'Mayonnaise', 0, 3, 'mayonnaise（スペインのメノルカ島の港町マオンが由来という説がある）', 'mayonnaise', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ケチャップ', 'Ketchup', 0, 3, 'ketchup（中国南部の魚醤の呼び名が語源という説）', 'ketchup', 'サンドウィッチの材料。', ['ing']],
  ['food', 'マスタード', 'Mustard', 0, 3, 'mustard', 'mustard', 'サンドウィッチの材料。', ['ing']],
  ['food', 'バター', 'Butter', 0, 3, 'butter', 'butter', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ソルト', 'Salt', 0, 3, 'salt。「塩」ではなく英語の呼び方', 'salt', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ペッパー', 'Pepper', 0, 3, 'pepper。「こしょう」ではなく英語の呼び方', 'pepper', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ヨーグルト', 'Yogurt', 0, 3, 'yogurt（トルコ語から）', 'yogurt', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ホイップクリーム', 'Whipped Cream', 0, 3, 'whipped cream（泡立てたクリーム）', 'whipped cream', 'サンドウィッチの材料。', ['ing']],
  ['food', 'クリームチーズ', 'Cream Cheese', 0, 3, 'cream cheese', 'cream cheese', 'サンドウィッチの材料。', ['ing']],
  ['food', 'マーマレード', 'Marmalade', 0, 3, 'marmalade（ポルトガル語の marmelada＝マルメロのジャムから）', 'marmalade', 'サンドウィッチの材料。', ['ing']],
  ['food', 'オリーブオイル', 'Olive Oil', 0, 3, 'olive oil。パルデアの名物オリーブ', 'olive oil', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ビネガー', 'Vinegar', 0, 3, 'vinegar（フランス語の vin aigre＝酸っぱいワイン から）', 'vinegar', 'サンドウィッチの材料。', ['ing']],
  ['food', 'ひでん：あまスパイス', 'Sweet Herba Mystica', 1, 3, '秘伝＋甘（あま）＋spice', 'sweet＋herba mystica（ラテン語で「神秘の草」）', 'ヌシポケモンのいる場所で見つかる秘伝スパイス。', ['ing']],
  ['food', 'ひでん：しおスパイス', 'Salty Herba Mystica', 1, 3, '秘伝＋塩（しお）＋spice', 'salty＋herba mystica（ラテン語で「神秘の草」）', 'ヌシポケモンのいる場所で見つかる秘伝スパイス。', ['ing']],
  ['food', 'ひでん：すぱスパイス', 'Sour Herba Mystica', 1, 3, '秘伝＋酸っぱ（すっぱ）＋spice', 'sour＋herba mystica（ラテン語で「神秘の草」）', 'ヌシポケモンのいる場所で見つかる秘伝スパイス。', ['ing']],
  ['food', 'ひでん：にがスパイス', 'Bitter Herba Mystica', 1, 3, '秘伝＋苦（にが）＋spice', 'bitter＋herba mystica（ラテン語で「神秘の草」）', 'ヌシポケモンのいる場所で見つかる秘伝スパイス。', ['ing']],
  ['food', 'ひでん：からスパイス', 'Spicy Herba Mystica', 1, 3, '秘伝＋辛（から）＋spice', 'spicy＋herba mystica（ラテン語で「神秘の草」）', 'ヌシポケモンのいる場所で見つかる秘伝スパイス。', ['ing']],

  // ===== ピクニック =====
  ['food', '食事パワー', 'Meal Power', 0, 3, '食事＋power', 'meal（食事）＋power', 'サンドウィッチでは、材料それぞれに決まっている「味」「パワー」「タイプ」の値を足し合わせて、上位のものから食事パワーが決まる（ゲーム内には表示されない内部の値）。いちばん強い味と2番目の味の組み合わせでボーナスが付くパワーが決まっていて、たとえば甘み＋塩みならタマゴパワー、辛み＋塩みならでかでかパワーになる。サンドウィッチや料理を食べると得られる効果。「そうぐうパワー」「ほかくパワー」など。'],
  ['food', 'サンドウィッチのランク', 'Sandwich tiers', 1, 3, 'スーパー・ハイパー・マスター。モンスターボールの「スーパーボール・ハイパーボール・マスターボール」と同じ並び', 'Great・Ultra・Master。ボールの英語名「Great Ball・Ultra Ball・Master Ball」と同じ並び', 'レシピの上位版の名前は、日英ともボールの格の呼び方と対応している。'],

  // ===== ファッション（ブランド） =====
  ['fashion', 'DENSOKU', 'DENSOKU', 1, 2, ['電速（でんそく）？ 速さを思わせる響き', 'スポーツ用品らしい名前'], '日本語版と同じ（ロゴ表記）', 'スポーツ系の服のブランド。', ['brand']],
  ['fashion', 'YOCINOSOMEI', 'YOCINOSOMEI', 1, 3, ['ソメイヨシノ（染井吉野、桜の品種）を前後入れ替えた名前', '吉野（よしの）＋染井（そめい）'], '日本語版と同じ（ロゴ表記）', '上品な服のブランド。', ['brand']],
  ['fashion', 'SO ATUMORI', 'SO ATUMORI', 1, 2, ['「そう、あつもり（厚盛り・熱盛り）」', '平敦盛（あつもり）の響き'], '日本語版と同じ（ロゴ表記）', 'レザー系の服のブランド。', ['brand']],
  ['fashion', 'BROTHERFOOT', 'BROTHERFOOT', 1, 2, ['brother（兄弟）＋foot（足）', '「あしのとも（足の友）」と同じく足元の相棒の意味'], '日本語版と同じ（ロゴ表記）', '靴・靴下のブランド。', ['brand']],
  ['fashion', 'STARCRAZY', 'STARCRAZY', 1, 2, 'star（星）＋crazy（夢中な）', '日本語版と同じ（ロゴ表記）', 'ポップな服のブランド。', ['brand']],
  ['fashion', 'DOPEGRANMA', 'DOPEGRANMA', 1, 2, ['dope（イケてる、スラング）＋granma（おばあちゃん）', 'おばあちゃんの手編みのようなニットの雰囲気'], '日本語版と同じ（ロゴ表記）', 'ニット帽などのブランド。', ['brand']],
  ['fashion', 'DECA SPORTS', 'DECA SPORTS', 1, 2, ['deca（ギリシャ語で10、十種競技 decathlon）＋sports', '「でか（大きい）」の響き'], '日本語版と同じ（ロゴ表記）', 'スポーツ用品のブランド。', ['brand']],
  ['fashion', 'MOTHAT', 'MOTHAT', 1, 2, ['mo（もっと）＋hat（帽子）', 'mother＋hat'], '日本語版と同じ（ロゴ表記）', '帽子のブランド。', ['brand']],
  ['fashion', 'DEFOG', 'DEFOG', 1, 3, 'defog（くもり止め）', '日本語版と同じ（ロゴ表記）', '眼鏡のブランド。レンズのくもり止めにちなむ名前。', ['brand']],
  ['fashion', 'ULINGEAR', 'ULINGEAR', 1, 2, ['ウリン（堅い木材）＋gear（装備）', 'ride on＋gear の響き'], '日本語版と同じ（ロゴ表記）', 'ヘルメット・ライド用品のブランド。', ['brand']],
  ['fashion', 'Ortiga', 'Ortiga', 1, 3, 'ortiga（スペイン語でイラクサ）。スター団のオルティガと同じ名前', '日本語版と同じ（ロゴ表記）', 'ヘルメットのブランド。スター団のオルティガと同じ名前で、関係が気になるところ。', ['brand']],
  ['fashion', 'Ruggle', 'Ruggle', 1, 1, ['rugged（ごつごつした、丈夫な）', 'rug（敷物）'], '日本語版と同じ（ロゴ表記）', '革小物などのブランド。', ['brand']],
  ['fashion', 'Chica', 'Chica', 1, 3, 'chica（スペイン語で女の子）', '日本語版と同じ（ロゴ表記）', 'かわいい柄の靴下などのブランド。', ['brand']],
  ['fashion', 'ALL AGES', 'ALL AGES', 1, 3, 'all ages（全年齢向け）', '日本語版と同じ（ロゴ表記）', '定番アイテムのブランド。', ['brand']],

  // ===== ファッション（アイテム） =====


  // ===== 地名（追加） =====
  ['place', 'コサジの小道', 'Poco Path', 0, 3, 'コサジ（町）＋小道', 'Poco（Cabo Poco）＋path', '', ['area']],
  ['place', '入り江のほら穴', 'Inlet Grotto', 0, 3, '入り江（いりえ）＋洞穴', 'inlet（入り江）＋grotto（洞窟）', '', ['area']],
  ['place', 'しるしの木立ち', 'Tagtree Thicket', 1, 3, '印（しるし）＋木立ち。落書き（タギング）の印が付いた木々', 'tag（落書きの印）＋tree＋thicket（茂み）', 'タギングル（Grafaiai）の「タギング」とつながる。', ['area']],
  ['place', 'プルピケ山道', 'Dalizapa Passage', 1, 2, ['プル（引っ張る）＋ピケ（ピケタウン）', 'pull＋piquer'], ['dali? ＋zapa（Zapapico）', 'Dalí（画家）の響き'], 'ピケタウンとチャンプルタウンを結ぶ山道。', ['area']],
  ['place', 'ベイク空洞', 'Alfornada Cavern', 1, 3, 'ベイク（ベイクタウン）＋空洞', 'Alfornada＋cavern（洞窟）', '', ['area']],
  ['place', 'オコゲ林道', 'Socarrat Trail', 1, 3, 'おこげ（ごはんの焦げ）', 'socarrat（パエリアの鍋底のおこげ）', 'オージャ（鍋）の湖のそばにある林道。日英とも鍋のおこげ。', ['area']],
  ['place', '朽木の祠', 'Grasswither Shrine', 2, 3, '朽木（くちき）の祠（ほこら）', 'grass（草）＋wither（枯れる）＋shrine', '災厄のポケモンが封じられた祠。', ['shrine']],
  ['place', '凍裂の祠', 'Icerend Shrine', 2, 3, '凍裂（とうれつ＝凍って裂ける）の祠', 'ice＋rend（引き裂く）＋shrine', '災厄のポケモンが封じられた祠。', ['shrine']],
  ['place', '塵土の祠', 'Groundblight Shrine', 2, 3, '塵土（じんど＝ちりと土）の祠', 'ground＋blight（荒廃）＋shrine', '災厄のポケモンが封じられた祠。', ['shrine']],
  ['place', '火難の祠', 'Firescourge Shrine', 2, 3, '火難（かなん＝火による災い）の祠', 'fire＋scourge（災い）＋shrine', '災厄のポケモンが封じられた祠。', ['shrine']],
  ['place', 'ゼロゲート', 'Zero Gate', 2, 3, 'zero（エリアゼロ）＋gate（門）', 'Zero＋gate', ''],
  ['place', 'パルデア十景', 'Ten Sights of Paldea', 0, 3, '十景（じっけい＝10の名所）', 'ten sights（10の名所）', 'パルデア各地の名所10か所。'],
  ['place', 'オリーブ大農園', 'Grand Olive Orchard', 0, 3, 'olive＋大農園', 'grand＋olive orchard', 'パルデア十景。オリーブはスペインの特産品。', ['sight']],
  ['place', 'ひそやかビーチ', 'Secluded Beach', 1, 3, 'ひそやか（ひっそりした）＋beach', 'secluded（人目につかない）＋beach', 'パルデア十景。', ['sight']],
  ['place', '列柱洞', 'Colonnade Hollow', 1, 3, '列柱（れっちゅう＝柱の並び）＋洞', 'colonnade（列柱）＋hollow（くぼみ）', 'パルデア十景。', ['sight']],
  ['place', '100万ボルトの夜景', 'Million Volt Skyline', 1, 3, ['「100万ドルの夜景」のもじり', 'でんきタイプの技「10まんボルト」の響き'], ['million-dollar view（100万ドルの眺め）のもじり', 'million volt（100万ボルト）'], 'パルデア十景。ハッコウシティの夜景。', ['sight']],
  ['place', 'ビシャビシャの斜塔', 'Leaking Tower of Paldea', 1, 3, 'ピサの斜塔のもじり（ピサ→ビシャビシャ）', 'Leaning Tower of Pisa（ピサの斜塔）のもじり（leaning→leaking）', 'パルデア十景。滝のそばで水びたしの塔。日英とも斜塔のもじり。', ['sight']],
  ['place', 'みだれづきの滝', 'Fury Falls', 1, 3, ['乱れ突き（技「みだれづき」）', '乱れて落ちる滝'], ['fury（激怒）＋falls', '技「みだれづき」の英語名 Fury Attack の fury'], 'パルデア十景。日英とも技の名前にかけた名所。', ['sight']],
  ['place', 'ありがた岩', 'Gracia Stones', 1, 3, 'ありがたい＋岩', 'gracia（スペイン語で恵み。gracias＝ありがとう）＋stones', 'パルデア十景。日英とも「ありがとう」の響き。', ['sight']],
  ['place', 'オージャの大滝', 'Casseroya Falls', 1, 3, 'オージャ（湖）＋大滝', 'Casseroya＋falls', 'パルデア十景。', ['sight']],
  ['place', 'ナッペの手', "Glaseado's Grasp", 1, 3, 'ナッペ（山）＋手', 'Glaseado＋grasp（つかむこと）', 'パルデア十景。手のような形の岩。', ['sight']],
  ['place', 'パルデア最高峰', "Paldea's Highest Peak", 1, 3, 'パルデア＋最高峰', "Paldea's highest peak", 'パルデア十景。', ['sight']],

  // ===== 人物・用語（追加） =====
  ['person', 'ネルケ', 'Clive', 2, 2, ['Nelke（ドイツ語でカーネーション）', '校長クラベル（スペイン語 clavel＝カーネーション）と同じ花'], ['clove（クローブ）。カーネーションの英名 clove pink とも関わる', 'Clavell と頭文字・響きが近い'], 'スター団に関わる謎の転校生。日英とも「カーネーション」に行き着く名前。'],
  ['term', 'スター団アジト', 'Team Star base', 1, 3, 'スター団＋アジト（隠れ家、agitpunkt から）', 'Team Star＋base（基地）', '']
].map(([c, ja, en, sp, cf, jo, eo, ev = '', t]) => (t ? { c, ja, en, sp, cf, jo, eo, ev, t } : { c, ja, en, sp, cf, jo, eo, ev }));

if (typeof module !== 'undefined') module.exports = LIFE_ENTRIES;
