/*
 * ポケモンSV元ネタ推測図鑑 ― アイテムの収録データ（追加分・その2）
 *
 * [日本語名, 英語名, ネタバレ段階, 確からしさ, 日本語名の由来, 英語名の由来, 補足（任意）, タグ（任意）]
 * 由来は文字列か、諸説あるときは配列。名前は Bulbapedia・ポケモンWiki で日英を照らし合わせています。
 */
var ITEM2_ENTRIES = [
  // --- ボール（残り） ---

  // --- 回復・飲み物 ---
  ['おいしいみず', 'Fresh Water', 0, 3, 'おいしい水', 'fresh water（新鮮な水）', '自動販売機で売られるシリーズ伝統の飲み物。'],
  ['サイコソーダ', 'Soda Pop', 0, 3, ['サイコー（最高）＋ソーダ', 'psycho（超能力）＋soda'], 'soda pop（炭酸飲料）', 'シリーズ伝統の飲み物。'],
  ['ミックスオレ', 'Lemonade', 0, 3, 'mix＋au lait（フランス語で「牛乳入り」）', 'lemonade（レモネード）', '日本語版は果物と牛乳を混ぜた飲み物、英語版はレモネードと、中身の印象が違う。'],
  ['モーモーミルク', 'Moomoo Milk', 0, 3, 'モーモー（牛の鳴き声、ミルタンク）＋milk', 'moo moo（牛の鳴き声）＋milk', '日英とも牛の鳴き声。'],
  ['ちからのこな', 'Energy Powder', 1, 3, '力の粉。漢方薬', 'energy＋powder', '苦い漢方薬のシリーズ（ポケモンのなつき度が下がる）。'],
  ['ちからのねっこ', 'Energy Root', 1, 3, '力の根っこ', 'energy＋root', '苦い漢方薬のシリーズ。'],
  ['ばんのうごな', 'Heal Powder', 1, 3, '万能粉（ばんのうこな）', 'heal＋powder', '苦い漢方薬のシリーズ。'],
  ['ふっかつそう', 'Revival Herb', 1, 3, '復活草', 'revival（復活）＋herb', '苦い漢方薬のシリーズ。'],
  ['ピーピーリカバー', 'Max Ether', 1, 3, 'PP＋recover（回復する）', 'max＋ether（霊薬エーテル）', ''],
  ['ピーピーエイダー', 'Elixir', 1, 3, 'PP＋aider（助ける者）', 'elixir（霊薬）', ''],

  // --- ドーピングアイテム ---
  ['マックスアップ', 'HP Up', 1, 3, 'max（最大）＋up。最大HPの基礎ポイントを上げる', 'HP＋up', 'HPの基礎ポイントを上げる薬。'],
  ['タウリン', 'Protein', 1, 3, 'taurine（タウリン、栄養ドリンクに入っているアミノ酸の一種）', 'protein（たんぱく質、筋肉のもと）', '攻撃を上げる薬。日英とも「体づくり」を思わせる栄養素の名前。'],
  ['ブロムヘキシン', 'Iron', 1, 3, 'bromhexine（ブロムヘキシン、実在するせき止め・たん切りの薬の成分）', 'iron（鉄。鉄のように硬い＝防御）', '防御を上げる薬。日本語版は薬の成分名、英語版は栄養素の名前。'],
  ['リゾチウム', 'Calcium', 1, 3, 'lysozyme（リゾチーム、風邪薬などに入る酵素）の響き', 'calcium（カルシウム）', '特攻を上げる薬。'],
  ['キトサン', 'Zinc', 1, 3, 'chitosan（キトサン、カニの殻などからとれる健康食品の成分）', 'zinc（亜鉛）', '特防を上げる薬。'],
  ['インドメタシン', 'Carbos', 1, 3, 'indometacin（インドメタシン、実在する痛み止めの成分）', 'carbohydrates（炭水化物）の略', '素早さを上げる薬。'],
  ['ポイントアップ', 'PP Up', 1, 3, 'PP（ポイント）＋up', 'PP＋up', '技の使用回数（PP）の最大値を上げる。'],
  ['ポイントマックス', 'PP Max', 2, 3, 'PP（ポイント）＋max', 'PP＋max', ''],
  ['たいりょくのハネ', 'Health Feather', 1, 3, '体力の羽', 'health（体力）＋feather', '基礎ポイントを少し上げる羽のシリーズ。'],
  ['きんりょくのハネ', 'Muscle Feather', 1, 3, '筋力の羽', 'muscle（筋肉）＋feather', ''],
  ['ていこうのハネ', 'Resist Feather', 1, 3, '抵抗の羽', 'resist（抵抗）＋feather', ''],
  ['ちりょくのハネ', 'Genius Feather', 1, 3, '知力の羽', 'genius（天才）＋feather', ''],
  ['せいしんのハネ', 'Clever Feather', 1, 3, '精神の羽', 'clever（かしこい）＋feather', '特防を上げる羽。日本語は精神、英語はかしこさで、知力の羽と入れ替わったような名前になっている。'],
  ['しゅんぱつのハネ', 'Swift Feather', 1, 3, '瞬発の羽', 'swift（すばやい）＋feather', ''],
  ['きれいなハネ', 'Pretty Feather', 1, 3, 'きれいな羽', 'pretty＋feather', '売るためのきれいな羽。'],

  // --- バトル用の使い捨て道具 ---
  ['エフェクトガード', 'Guard Spec.', 1, 3, 'effect（能力変化の効果）＋guard', 'guard（守る）＋spec.（special の略）', ''],
  ['クリティカット', 'Dire Hit', 1, 3, 'critical（急所）＋cut（一撃）', 'dire（ひどい、痛烈な）＋hit', '急所に当たりやすくする。'],
  ['プラスパワー', 'X Attack', 1, 3, 'plus＋power', 'X（特別な）＋attack', '攻撃を上げる。'],
  ['ディフェンダー', 'X Defense', 1, 3, 'defender（守る人）', 'X＋defense', ''],
  ['スピーダー', 'X Speed', 1, 3, 'speed＋-er', 'X＋speed', ''],
  ['ヨクアタール', 'X Accuracy', 1, 3, '「よく当たる」を薬の名前風にしたもの', 'X＋accuracy（命中率）', '日本語版は薬の商品名のようなしゃれ。'],
  ['スペシャルアップ', 'X Sp. Atk', 1, 3, 'special（特殊）＋up', 'X＋Sp. Atk（特攻）', ''],
  ['スペシャルガード', 'X Sp. Def', 1, 3, 'special＋guard', 'X＋Sp. Def（特防）', ''],
  ['ピッピにんぎょう', 'Poké Doll', 1, 3, 'ピッピ（ポケモン）＋人形', 'Poké＋doll', '日本語版はピッピ、英語版はポケモン全般の人形になっている。'],

  // --- 進化などに使う道具 ---
  ['まんまるいし', 'Oval Stone', 1, 3, 'まんまるな石', 'oval（楕円形の）＋stone', 'ピンプクの進化に使う。'],
  ['するどいツメ', 'Razor Claw', 1, 3, '鋭い爪', 'razor（かみそり）＋claw', 'ニューラの進化に使う。'],
  ['かわらずのいし', 'Everstone', 1, 3, '変わらずの石', 'ever（ずっと）＋stone', '持たせると進化しなくなる。'],

  // --- 持ち物 ---
  ['ひかりのこな', 'Bright Powder', 1, 3, '光の粉', 'bright（明るい）＋powder', ''],
  ['せんせいのツメ', 'Quick Claw', 1, 3, '先制の爪', 'quick＋claw', ''],
  ['やすらぎのすず', 'Soothe Bell', 1, 3, '安らぎの鈴', 'soothe（なだめる）＋bell', ''],
  ['ぎんのこな', 'Silver Powder', 1, 3, '銀の粉', 'silver＋powder', ''],
  ['おまもりこばん', 'Amulet Coin', 1, 3, 'お守り＋小判', 'amulet（お守り）＋coin', 'もらえるお金が増える。'],
  ['きよめのおふだ', 'Cleanse Tag', 1, 3, '清めのお札', 'cleanse（清める）＋tag（札）', ''],
  ['けむりだま', 'Smoke Ball', 1, 3, '煙玉（忍者の道具）', 'smoke＋ball', ''],
  ['しあわせタマゴ', 'Lucky Egg', 1, 3, '幸せ卵', 'lucky＋egg', ''],
  ['ピントレンズ', 'Scope Lens', 1, 3, 'ピント（焦点、オランダ語 brandpunt から）＋lens', 'scope（照準器）＋lens', '急所に当たりやすくなる。'],
  ['でんきだま', 'Light Ball', 1, 3, '電気玉', 'light（光）＋ball', 'ピカチュウ専用の持ち物。'],
  ['やわらかいすな', 'Soft Sand', 1, 3, '柔らかい砂', 'soft＋sand', 'じめん技を強くする。'],
  ['かたいいし', 'Hard Stone', 1, 3, '硬い石', 'hard＋stone', 'いわ技を強くする。'],
  ['きせきのタネ', 'Miracle Seed', 1, 3, '奇跡の種', 'miracle＋seed', 'くさ技を強くする。'],
  ['くろいメガネ', 'Black Glasses', 1, 3, '黒い眼鏡（サングラス）', 'black＋glasses', 'あく技を強くする。'],
  ['くろおび', 'Black Belt', 1, 3, '黒帯（柔道・空手の有段者の帯）', 'black belt', 'かくとう技を強くする。'],
  ['じしゃく', 'Magnet', 1, 3, '磁石', 'magnet', 'でんき技を強くする。'],
  ['しんぴのしずく', 'Mystic Water', 1, 3, '神秘の雫', 'mystic（神秘的な）＋water', 'みず技を強くする。'],
  ['するどいくちばし', 'Sharp Beak', 1, 3, '鋭いくちばし', 'sharp＋beak', 'ひこう技を強くする。'],
  ['どくバリ', 'Poison Barb', 1, 3, '毒針', 'poison＋barb（とげ）', 'どく技を強くする。'],
  ['とけないこおり', 'Never-Melt Ice', 1, 3, '溶けない氷', 'never-melt（決して溶けない）＋ice', 'こおり技を強くする。'],
  ['のろいのおふだ', 'Spell Tag', 1, 3, '呪いのお札', 'spell（呪文）＋tag', 'ゴースト技を強くする。'],
  ['まがったスプーン', 'Twisted Spoon', 1, 3, '曲がったスプーン（スプーン曲げ＝超能力）', 'twisted（ねじれた）＋spoon', 'エスパー技を強くする。'],
  ['もくたん', 'Charcoal', 1, 3, '木炭', 'charcoal', 'ほのお技を強くする。'],
  ['りゅうのキバ', 'Dragon Fang', 1, 3, '竜の牙', 'dragon＋fang', 'ドラゴン技を強くする。'],
  ['シルクのスカーフ', 'Silk Scarf', 1, 3, 'silk＋scarf', 'silk scarf', 'ノーマル技を強くする。'],
  ['かいがらのすず', 'Shell Bell', 1, 3, '貝殻の鈴', 'shell＋bell（韻を踏む）', ''],
  ['こうかくレンズ', 'Wide Lens', 1, 3, '広角レンズ', 'wide（広い）＋lens', ''],
  ['ちからのハチマキ', 'Muscle Band', 1, 3, '力の鉢巻き', 'muscle＋band', ''],
  ['ものしりメガネ', 'Wise Glasses', 1, 3, '物知り眼鏡', 'wise（賢い）＋glasses', ''],
  ['たつじんのおび', 'Expert Belt', 1, 3, '達人の帯', 'expert＋belt', ''],
  ['どくどくだま', 'Toxic Orb', 1, 3, '毒々玉', 'toxic＋orb', ''],
  ['かえんだま', 'Flame Orb', 1, 3, '火炎玉', 'flame＋orb', ''],
  ['フォーカスレンズ', 'Zoom Lens', 1, 3, 'focus（焦点）＋lens', 'zoom＋lens', ''],
  ['メトロノーム', 'Metronome', 1, 3, 'metronome（拍子を刻む道具）', 'metronome', '同じ技を続けると威力が上がる。'],
  ['くろいてっきゅう', 'Iron Ball', 1, 3, '黒い鉄球', 'iron＋ball', ''],
  ['こうこうのしっぽ', 'Lagging Tail', 1, 3, '後攻の尻尾', 'lagging（遅れる）＋tail', ''],
  ['あかいいと', 'Destiny Knot', 1, 3, '赤い糸（運命の赤い糸）', 'destiny（運命）＋knot（結び目）', '日英とも「運命」。'],
  ['つめたいいわ', 'Icy Rock', 1, 3, '冷たい岩', 'icy＋rock', '雪の天気を長くする。'],
  ['さらさらいわ', 'Smooth Rock', 1, 3, 'さらさら（砂の音）の岩', 'smooth（なめらかな）＋rock', '砂嵐を長くする。'],
  ['あついいわ', 'Heat Rock', 1, 3, '熱い岩', 'heat＋rock', '晴れを長くする。'],
  ['しめったいわ', 'Damp Rock', 1, 3, '湿った岩', 'damp（湿った）＋rock', '雨を長くする。'],
  ['ねばりのかぎづめ', 'Grip Claw', 1, 3, '粘りの鉤爪', 'grip（つかむ）＋claw', ''],
  ['くっつきバリ', 'Sticky Barb', 1, 3, 'くっつき＋針', 'sticky（くっつく）＋barb', ''],
  ['パワーリスト', 'Power Bracer', 1, 3, 'power＋wrist（手首）', 'power＋bracer（腕当て）', '素早さが下がる代わりに努力値がたまるパワー系の持ち物。'],
  ['パワーベルト', 'Power Belt', 1, 3, 'power＋belt', 'power＋belt', ''],
  ['パワーレンズ', 'Power Lens', 1, 3, 'power＋lens', 'power＋lens', ''],
  ['パワーバンド', 'Power Band', 1, 3, 'power＋band', 'power＋band', ''],
  ['パワーアンクル', 'Power Anklet', 1, 3, 'power＋anklet（足首飾り）', 'power＋anklet', ''],
  ['パワーウエイト', 'Power Weight', 1, 3, 'power＋weight（おもり）', 'power＋weight', ''],
  ['きれいなぬけがら', 'Shed Shell', 1, 3, 'きれいな抜け殻', 'shed（脱ぎ捨てる）＋shell', ''],
  ['おおきなねっこ', 'Big Root', 1, 3, '大きな根っこ', 'big＋root', ''],
  ['かるいし', 'Float Stone', 1, 3, '軽石（かるいし、実在する穴の多い軽い石）', 'float（浮く）＋stone', ''],
  ['レッドカード', 'Red Card', 1, 3, 'red card（サッカーの退場処分）', 'red card', '攻撃してきた相手を交代させる。'],
  ['ねらいのまと', 'Ring Target', 1, 3, '狙いの的', 'ring（輪）＋target', ''],
  ['しめつけバンド', 'Binding Band', 1, 3, '締め付け＋band', 'binding（しばる）＋band', ''],
  ['きゅうこん', 'Absorb Bulb', 1, 3, ['球根（きゅうこん）', '吸（きゅう）＝吸収の掛け言葉'], 'absorb（吸収する）＋bulb（球根）', 'みず技を受けると特攻が上がる。'],
  ['じゅうでんち', 'Cell Battery', 1, 3, '充電池', 'cell＋battery', 'でんき技を受けると攻撃が上がる。'],
  ['ノーマルジュエル', 'Normal Gem', 1, 3, 'normal＋jewel', 'normal＋gem', ''],
  ['ひかりごけ', 'Luminous Moss', 1, 3, '光苔（ひかりごけ、実在する光る苔）', 'luminous（光る）＋moss', ''],
  ['ゆきだま', 'Snowball', 1, 3, '雪玉', 'snowball', ''],
  ['ぼうじんゴーグル', 'Safety Goggles', 1, 3, '防塵（ぼうじん＝ほこりを防ぐ）＋goggles', 'safety＋goggles', ''],
  ['ビビリだま', 'Adrenaline Orb', 1, 3, 'ビビリ（怖がり）＋玉', 'adrenaline（アドレナリン）＋orb', '「いかく」を受けると素早さが上がる。日本語はびびる、英語は興奮ホルモン。'],
  ['グランドコート', 'Terrain Extender', 1, 3, 'ground＋coat（覆う）', 'terrain（地形・フィールド）＋extender（延長するもの）', 'フィールドを長くする。'],
  ['ぼうごパット', 'Protective Pads', 1, 3, '防護＋pad', 'protective＋pads', ''],
  ['エレキシード', 'Electric Seed', 1, 3, 'electric＋seed', 'electric＋seed', '「エレキフィールド」で効果が出る種のシリーズ。'],
  ['サイコシード', 'Psychic Seed', 1, 3, 'psycho＋seed', 'psychic＋seed', ''],
  ['ミストシード', 'Misty Seed', 1, 3, 'mist＋seed', 'misty＋seed', ''],
  ['グラスシード', 'Grassy Seed', 1, 3, 'grass＋seed', 'grassy＋seed', ''],
  ['のどスプレー', 'Throat Spray', 1, 3, 'のど＋spray', 'throat（のど）＋spray', '音の技を使うと特攻が上がる。'],
  ['だっしゅつパック', 'Eject Pack', 1, 3, '脱出＋pack', 'eject（射出する）＋pack', ''],
  ['からぶりほけん', 'Blunder Policy', 1, 3, '空振り保険', 'blunder（しくじり）＋policy（保険証券）', ''],



  // --- お宝 ---
  ['ちいさなキノコ', 'Tiny Mushroom', 1, 3, '小さなきのこ', 'tiny＋mushroom', '売るためのお宝。'],
  ['おおきなキノコ', 'Big Mushroom', 1, 3, '大きなきのこ', 'big＋mushroom', ''],
  ['かおるキノコ', 'Balm Mushroom', 1, 3, '香るきのこ', 'balm（香油）＋mushroom', ''],
  ['しんじゅ', 'Pearl', 1, 3, '真珠', 'pearl', ''],
  ['おおきなしんじゅ', 'Big Pearl', 1, 3, '大きな真珠', 'big＋pearl', ''],
  ['おだんごしんじゅ', 'Pearl String', 1, 3, 'お団子（のように連なった）真珠', 'pearl string（真珠の連なり）', ''],
  ['ほしのすな', 'Stardust', 1, 3, '星の砂', 'stardust（星くず）', ''],
  ['ほしのかけら', 'Star Piece', 1, 3, '星の欠片', 'star＋piece', ''],
  ['すいせいのかけら', 'Comet Shard', 1, 3, '彗星の欠片', 'comet＋shard', ''],
  ['きんのたま', 'Nugget', 1, 3, '金の玉', 'nugget（金塊）', 'シリーズ伝統の換金アイテム。'],
  ['でかいきんのたま', 'Big Nugget', 1, 3, 'でかい＋金の玉', 'big＋nugget', ''],
  // --- 姿を変える道具（本編で手に入るもの） ---
  ['くれないのミツ', 'Red Nectar', 1, 3, ['紅（くれない＝あざやかな赤）＋蜜', '赤い花の蜜'], 'red＋nectar（花の蜜）', 'オドリドリに使うと、めらめらスタイル（ほのお）に変わる。本作ではジムバッジを3個手に入れるとデリバードポーチで買える。'],
  ['やまぶきのミツ', 'Yellow Nectar', 1, 3, '山吹色（やまぶきいろ＝黄色）＋蜜', 'yellow＋nectar', 'オドリドリに使うと、ぱちぱちスタイル（でんき）に変わる。'],
  ['うすもものミツ', 'Pink Nectar', 1, 3, '薄桃色（うすももいろ＝淡いピンク）＋蜜', 'pink＋nectar', 'オドリドリに使うと、ふらふらスタイル（エスパー）に変わる。'],
  ['むらさきのミツ', 'Purple Nectar', 1, 3, '紫（むらさき）＋蜜', 'purple＋nectar', 'オドリドリに使うと、まいまいスタイル（ゴースト）に変わる。日本語は昔ながらの色の名前（紅・山吹・薄桃・紫）でそろえている。'],
  ['ロトムのカタログ', 'Rotom Catalog', 1, 3, 'ロトム＋catalog（商品の一覧）。ロトムが好きな家電が載っている', 'Rotom＋catalog', 'ロトムを家電（電子レンジ・洗濯機・冷蔵庫・扇風機・芝刈り機）に入れたり出したりできる。本作では、ロトムを連れているときにマリナードタウンの競りに出ることがある。'],
  ['あまいミツ', 'Honey', 1, 3, '甘い蜜', 'honey（はちみつ）', ''],
  ['きちょうなホネ', 'Rare Bone', 1, 3, '貴重な骨', 'rare＋bone', ''],
  ['ちいさなタケノコ', 'Tiny Bamboo Shoot', 1, 3, '小さな筍', 'tiny＋bamboo shoot', ''],
  ['おおきなタケノコ', 'Big Bamboo Shoot', 1, 3, '大きな筍', 'big＋bamboo shoot', ''],

  // --- きのみ（残り） ---
  ['フィラのみ', 'Figy Berry', 1, 2, ['fig（イチジク）の響き', 'フィラ'], 'fig（イチジク）', '', ['berry']],
  ['ウイのみ', 'Wiki Berry', 1, 2, 'キウイの「ウイ」', 'kiwi の並べ替え', '', ['berry']],
  ['マゴのみ', 'Mago Berry', 1, 3, 'mango（マンゴー）', 'mango（マンゴー）の変形', '', ['berry']],
  ['バンジのみ', 'Aguav Berry', 1, 3, '蕃石榴（ばんじろう＝グアバの和名）', 'guava の並べ替え', '', ['berry']],
  ['イアのみ', 'Iapapa Berry', 1, 3, 'パパイアの「イア」', 'papaya の並べ替え', '', ['berry']],
  ['ザロクのみ', 'Pomeg Berry', 1, 3, '石榴（ざくろ）の並べ替え', 'pomegranate（ザクロ）', '', ['berry']],
  ['ネコブのみ', 'Kelpsy Berry', 1, 3, '根昆布（ねこぶ）', 'kelp（昆布）', '', ['berry']],
  ['タポルのみ', 'Qualot Berry', 1, 2, 'loquat（ロクワット＝ビワ）の読みを逆さにして崩した形とされる', 'loquat（ビワ）の並べ替え', '見た目はビワやキンカンに似ている。日本語名がなぜ「タポル」になるのかは、はっきり分からない。', ['berry']],
  ['ロメのみ', 'Hondew Berry', 1, 2, 'メロ（メロン）の逆さ読み', 'honeydew（ハネデューメロン）', '', ['berry']],
  ['ウブのみ', 'Grepa Berry', 1, 3, 'ぶどう（葡萄）の音を並べ替えた形（ぶどう→うぶ）', 'grape（ブドウ）の並べ替え', '名前はブドウだが、見た目はダイコン（カブ）のよう。', ['berry']],
  ['マトマのみ', 'Tamato Berry', 1, 3, 'トマトの並べ替え', 'tomato の並べ替え', '', ['berry']],
  ['オッカのみ', 'Occa Berry', 1, 3, 'カカオの並べ替え', 'cacao の並べ替え', 'ほのお技のダメージを弱める半減きのみ。', ['berry']],
  ['イトケのみ', 'Passho Berry', 1, 2, 'トケイ（時計草＝パッションフルーツの花）の並べ替え', 'passion fruit', 'みず技を弱める。', ['berry']],
  ['ソクノのみ', 'Wacan Berry', 1, 3, '蝋燭の木（ろうそくのき、キャンドルツリー）の「そくのき」', ['wax（ろう）＋candle（ろうそく）', 'candle tree（キャンドルツリー）'], 'でんき技を弱める。日英とも「ろうそくの木」が由来とみられる。', ['berry']],
  ['リンドのみ', 'Rindo Berry', 1, 3, ['タマリンド（tamarind、マメの仲間の果物）の後ろの部分', '竜胆（りんどう）の響き'], 'tamarind の後ろの部分', 'くさ技を弱める。', ['berry']],
  ['ヤチェのみ', 'Yache Berry', 1, 3, 'チェリモヤ（南米の果物）の音を並べ替えた形', 'cherimoya（チェリモヤ）の一部を並べ替え', 'こおり技を弱める。', ['berry']],
  ['ヨプのみ', 'Chople Berry', 1, 3, 'chomphu（チョンプー、タイ語でレンブ＝ワックスアップル）', ['chomphu（タイ語でレンブ）', 'rose apple（フトモモ、レンブの仲間）'], 'かくとう技を弱める。', ['berry']],
  ['ビアーのみ', 'Kebia Berry', 1, 3, 'アケビ（akebia）の後半', 'akebia（アケビ）の並べ替え', 'どく技を弱める。', ['berry']],
  ['シュカのみ', 'Shuca Berry', 1, 3, 'カシューの並べ替え', 'cashew の並べ替え', 'じめん技を弱める。', ['berry']],
  ['バコウのみ', 'Coba Berry', 1, 3, 'ババコウ（babaco、パパイヤの仲間の果物）の後ろの部分', 'babaco の後ろの部分', 'ひこう技を弱める。', ['berry']],
  ['ウタンのみ', 'Payapa Berry', 1, 2, ['瓢箪（ひょうたん）の「たん」を崩した形', '見た目もヒョウタンに似ている'], 'papaya（パパイヤ）の並べ替え', 'エスパー技を弱める。日本語は見た目のヒョウタン、英語はパパイヤと、日英で元にした植物が違うとみられる。', ['berry']],
  ['タンガのみ', 'Tanga Berry', 1, 3, 'pitanga（ピタンガ、南米の果物）', 'pitanga', 'むし技を弱める。', ['berry']],
  ['ヨロギのみ', 'Charti Berry', 1, 3, 'チョロギ（草石蚕、お正月料理に使う巻き貝のような形の根）', 'Chinese artichoke（チョロギの英名）の一部', 'いわ技を弱める。', ['berry']],
  ['カシブのみ', 'Kasib Berry', 1, 3, ['仏手柑（ぶっしゅかん、指のような形のミカンの仲間）の音を崩した形', 'cassava（キャッサバ）の響き'], '日本語名をそのままローマ字にした形', 'ゴースト技を弱める。', ['berry']],
  ['ハバンのみ', 'Haban Berry', 1, 3, ['照葉蕃石榴（てりはばんじろう＝ストロベリーグアバ）の「はばん」', 'habanero（ハバネロ）の響き'], '日本語名をそのままローマ字にした形', 'ドラゴン技を弱める。', ['berry']],
  ['ナモのみ', 'Colbur Berry', 1, 3, 'オナモミ（葈耳、服にくっつく「くっつき虫」）の後ろの部分', 'cocklebur（オナモミ）の並べ替え', 'あく技を弱める。', ['berry']],
  ['リリバのみ', 'Babiri Berry', 1, 3, 'biribá（ビリバ、南米の果物）の並べ替え', 'biribá の並べ替え', 'はがね技を弱める。', ['berry']],
  ['ホズのみ', 'Chilan Berry', 1, 3, '鬼灯（ほおずき）の「ほず」', 'Chinese lantern（ホオズキの英名、中国のちょうちん）', 'ノーマル技を弱める。', ['berry']],
  ['ロゼルのみ', 'Roseli Berry', 1, 3, 'roselle（ローゼル、ハイビスカスの仲間）', 'roselle', 'フェアリー技を弱める。', ['berry']],
  ['チイラのみ', 'Liechi Berry', 1, 2, 'ライチ（茘枝＝レイシ）の変形', 'lychee', 'ピンチのときに能力を上げるきのみ。', ['berry']],
  ['リュガのみ', 'Ganlon Berry', 1, 3, '竜眼（りゅうがん＝ロンガン）', 'longan の並べ替え', '', ['berry']],
  ['カムラのみ', 'Salac Berry', 1, 2, 'Calamus zalacca（サラクの古い学名）の Calamus（カラムス）', 'salak（サラク、スネークフルーツ）', '見た目はサボテンにも似ている。', ['berry']],
  ['ヤタピのみ', 'Petaya Berry', 1, 3, 'ピタヤ（ドラゴンフルーツ）の逆さ読み', 'pitaya', '', ['berry']],
  ['ズアのみ', 'Apicot Berry', 1, 2, 'アンズ（杏）の並べ替え', 'apricot', '', ['berry']],
  ['サンのみ', 'Lansat Berry', 1, 2, 'ランサットの「サン」', 'langsat（ランサット、東南アジアの果物）', '', ['berry']],
  ['スターのみ', 'Starf Berry', 1, 3, 'star fruit（スターフルーツ）', 'star fruit', '', ['berry']],
  ['ナゾのみ', 'Enigma Berry', 1, 3, '謎（なぞ）', 'enigma（謎）', '', ['berry']],
  ['ミクルのみ', 'Micle Berry', 1, 3, 'miracle fruit（ミラクルフルーツ）', 'miracle fruit', '', ['berry']],
  ['イバンのみ', 'Custap Berry', 1, 2, '蕃荔枝（バンレイシ＝カスタードアップル）の響き', 'custard apple', '', ['berry']],
  ['ジャポのみ', 'Jaboca Berry', 1, 3, 'jaboticaba（ジャボチカバ、ブラジルの果物）', 'jaboticaba', '', ['berry']],
  ['レンブのみ', 'Rowap Berry', 1, 3, '蓮霧（レンブ＝ワックスアップル）', 'watery rose apple（ミズレンブ）を縮めた形', '', ['berry']],
  ['アッキのみ', 'Kee Berry', 1, 3, 'ackee（アキー、西アフリカ原産の果物）', 'ackee', '', ['berry']],
  ['タラプのみ', 'Maranga Berry', 1, 2, 'tarap（タラップ、マランに近い果物）', 'marang（マラン）', '', ['berry']],

  // --- 大切なもの ---
  ['あなぬけのヒモ', 'Escape Rope', 0, 3, '穴抜けのひも', 'escape＋rope', 'シリーズ伝統の道具。'],
  ['まるいおまもり', 'Oval Charm', 2, 3, '丸いお守り', 'oval（楕円）＋charm', 'タマゴが見つかりやすくなる。'],
  ['ひかるおまもり', 'Shiny Charm', 2, 3, '光るお守り', 'shiny（色違い）＋charm', '色違いのポケモンに出会いやすくなる。'],
  ['たんけんこころえ', 'Adventure Guide', 0, 3, '探検心得', 'adventure＋guide', 'アカデミーでもらう冒険の手引き。'],
  ['サンドウィッチ', 'Sandwich', 0, 3, 'sandwich（サンドウィッチ伯爵の名前から）', 'sandwich', '作ったサンドウィッチを持ち運ぶための道具。'],
  ['コライドンのボール', "Koraidon's Poké Ball", 2, 3, 'コライドン＋ボール', "Koraidon's Poké Ball", ''],
  ['ミライドンのボール', "Miraidon's Poké Ball", 2, 3, 'ミライドン＋ボール', "Miraidon's Poké Ball", ''],
  ['ハイダイのサイフ', "Kofu's Wallet", 1, 3, 'ハイダイ＋財布', "Kofu's wallet", 'ジムリーダーのハイダイが落とした財布。'],
  ['バゲット', 'Baguette', 1, 3, 'baguette（フランス語で「棒」、フランスパン）', 'baguette', 'サンドウィッチのパン。'],

  // --- ピクニック用品 ---
  ['ピクニックセット', 'Picnic Set', 0, 3, 'picnic＋set', 'picnic set', 'ピクニックを開く道具一式。', ['picnic']],
  ['スクールボトル', 'Academy Bottle', 0, 3, 'school＋bottle', 'academy＋bottle', '日本語は「スクール」、英語は「アカデミー」。', ['picnic']],
  ['スクールカップ', 'Academy Cup', 0, 3, 'school＋cup', 'academy＋cup', '', ['picnic']],
  ['スクールクロス', 'Academy Tablecloth', 0, 3, 'school＋cloth', 'academy＋tablecloth', '', ['picnic']],
  ['スクールボール', 'Academy Ball', 0, 3, 'school＋ball', 'academy＋ball', '', ['picnic']],
  ['みずたまボトル', 'Polka-Dot Bottle', 1, 3, '水玉＋bottle', 'polka-dot（水玉模様）＋bottle', '', ['picnic']],
  ['ストライプボトル', 'Striped Bottle', 1, 3, 'stripe＋bottle', 'striped＋bottle', '', ['picnic']],
  ['ダイヤボトル', 'Diamond Bottle', 1, 3, 'diamond（ひし形）＋bottle', 'diamond＋bottle', '', ['picnic']],
  ['たてストライプカップ', 'Striped Cup', 1, 3, '縦＋stripe＋cup', 'striped＋cup', '', ['picnic']],
  ['よこストライプカップ', 'Barred Cup', 1, 3, '横＋stripe＋cup', 'barred（横じまの）＋cup', '日本語は縦・横で区別し、英語は striped と barred で区別している。', ['picnic']],
  ['みずたまカップ', 'Polka-Dot Cup', 1, 3, '水玉＋cup', 'polka-dot＋cup', '', ['picnic']],
  ['フラワーカップ', 'Flower Pattern Cup', 1, 3, 'flower＋cup', 'flower pattern＋cup', '', ['picnic']],
  ['ダイヤカップ', 'Diamond Pattern Cup', 1, 3, 'diamond＋cup', 'diamond pattern＋cup', '', ['picnic']],
  ['ファイヤーカップ', 'Fire Pattern Cup', 1, 3, 'fire＋cup', 'fire pattern＋cup', '', ['picnic']],
  ['ピカチュウカップ', 'Pikachu Cup', 1, 3, 'ピカチュウ＋cup', 'Pikachu＋cup', '', ['picnic']],
  ['イーブイカップ', 'Eevee Cup', 1, 3, 'イーブイ＋cup', 'Eevee＋cup', '', ['picnic']],
  ['ヤドンカップ', 'Slowpoke Cup', 1, 3, 'ヤドン＋cup', 'Slowpoke＋cup', '', ['picnic']],
  ['ファンシークロス', 'Whimsical Tablecloth', 1, 3, 'fancy（かわいい）＋cloth', 'whimsical（気まぐれな、ファンタジーな）＋tablecloth', '', ['picnic']],
  ['ネイチャークロス', 'Leafy Tablecloth', 1, 3, 'nature＋cloth', 'leafy（葉の多い）＋tablecloth', '', ['picnic']],
  ['うらめしクロス', 'Spooky Tablecloth', 1, 3, 'うらめしや（幽霊の決まり文句）＋cloth', 'spooky（不気味な）＋tablecloth', '', ['picnic']],
  ['しょうぶクロス', 'Battle Tablecloth', 1, 3, '勝負＋cloth', 'battle＋tablecloth', '', ['picnic']],
  ['かいじゅうクロス', 'Monstrous Tablecloth', 1, 3, '怪獣＋cloth', 'monstrous（怪物のような）＋tablecloth', '', ['picnic']],
  ['くさむらモノクロス', 'B&W Grass Tablecloth', 1, 3, '草むら＋モノクロ（白黒）＋cloth。「モノクロ」と「クロス」が重なる言葉遊び', 'B&W（black and white）＋grass＋tablecloth', '初代のゲーム画面の草むらのような白黒の柄。', ['picnic']],
  ['マリルボール', 'Marill Ball', 1, 3, 'マリル＋ball', 'Marill＋ball', 'マリルの形のボール。', ['picnic']],
  ['けいとボール', 'Yarn Ball', 1, 3, '毛糸＋ball', 'yarn（毛糸）＋ball', '', ['picnic']],
  ['ゲーミングボール', 'Cyber Ball', 1, 3, 'gaming（ゲーム用の光る機器の雰囲気）＋ball', 'cyber＋ball', '', ['picnic']],
  ['バランスボール', 'Exercise Ball', 1, 3, 'balance ball（和製英語）', 'exercise ball', '日本語は和製英語、英語は本来の言い方。', ['picnic']],
  ['Rステンレスボトル', 'Steel Bottle (R)', 1, 3, 'R（赤）＋stainless＋bottle', 'steel bottle（R）', '', ['picnic']],
  ['シルバーチタンボトル', 'Silver Bottle', 1, 3, 'silver＋titanium＋bottle', 'silver bottle', '', ['picnic']],
  ['ゴールドチタンボトル', 'Gold Bottle', 1, 3, 'gold＋titanium＋bottle', 'gold bottle', '', ['picnic']],
  ['ゴールドピック', 'Gold Pick', 1, 3, 'gold＋pick（サンドウィッチに刺す飾り串）', 'gold pick', '', ['picnic']],
  ['ピカピカピック', 'Pika-Pika Pick', 1, 3, 'ピカピカ（ピカチュウ）＋pick', 'Pika-Pika＋pick', '', ['picnic']],
  ['パチピカピック', 'Winking Pika Pick', 1, 3, 'パチッ（ウインク）＋ピカ＋pick', 'winking（ウインクする）＋Pika＋pick', '', ['picnic']],
  ['ブイブイピック', 'Vee-Vee Pick', 1, 3, 'ブイブイ（イーブイ）＋pick', 'Vee-Vee＋pick', '', ['picnic']],
  ['ニコブイピック', 'Smiling Vee Pick', 1, 3, 'ニコッ（笑顔）＋ブイ＋pick', 'smiling＋Vee＋pick', '', ['picnic']],
  ['おいわいはなびピック', 'Party Sparkler Pick', 1, 3, 'お祝い＋花火＋pick', 'party＋sparkler（手持ち花火）＋pick', '', ['picnic']],
  ['ゆうしゃのけんピック', 'Heroic Sword Pick', 1, 3, '勇者の剣＋pick', 'heroic sword＋pick', '', ['picnic']],
  ['パラソルピック', 'Parasol Pick', 1, 3, 'parasol（日傘）＋pick', 'parasol pick', '', ['picnic']],
  ['あさやけおはなピック', 'Sunrise Flower Pick', 1, 3, '朝焼け＋お花＋pick', 'sunrise＋flower＋pick', '', ['picnic']],
  ['ブループレート', 'Blue Dish', 1, 3, 'blue＋plate（皿）', 'blue＋dish', 'ピクニックのお皿。日本語は plate（プレート）、英語は dish と、同じお皿を別の言葉で呼んでいる。', ['picnic']]
].map(([ja, en, sp, cf, jo, eo, ev = '', t]) => (t ? { c: 'item', ja, en, sp, cf, jo, eo, ev, t } : { c: 'item', ja, en, sp, cf, jo, eo, ev }));

// 決まった形の名前（まとめて作る）
(function () {
  const TYPES = [['ノーマル', 'Normal'], ['ほのお', 'Fire'], ['みず', 'Water'], ['でんき', 'Electric'], ['くさ', 'Grass'], ['こおり', 'Ice'], ['かくとう', 'Fighting'], ['どく', 'Poison'], ['じめん', 'Ground'], ['ひこう', 'Flying'], ['エスパー', 'Psychic'], ['むし', 'Bug'], ['いわ', 'Rock'], ['ゴースト', 'Ghost'], ['ドラゴン', 'Dragon'], ['あく', 'Dark'], ['はがね', 'Steel'], ['フェアリー', 'Fairy']];
  TYPES.forEach(([ja, en]) => ITEM2_ENTRIES.push({ c: 'item', ja: 'テラピース' + ja, en: en + ' Tera Shard', sp: 0, cf: 3, jo: 'テラピース＋' + ja + '（タイプ名）', eo: en + '（タイプ名）＋tera shard', ev: 'テラスタイプを' + ja + 'に変えるのに使うかけら。日本語はタイプ名が後ろ、英語は前に付く。', t: ['shard'] }));
  const MINTS = [['さみしがり', 'Lonely'], ['いじっぱり', 'Adamant'], ['やんちゃ', 'Naughty'], ['ゆうかん', 'Brave'], ['ずぶとい', 'Bold'], ['わんぱく', 'Impish'], ['のうてんき', 'Lax'], ['のんき', 'Relaxed'], ['ひかえめ', 'Modest'], ['おっとり', 'Mild'], ['うっかりや', 'Rash'], ['れいせい', 'Quiet'], ['おだやか', 'Calm'], ['おとなしい', 'Gentle'], ['しんちょう', 'Careful'], ['なまいき', 'Sassy'], ['おくびょう', 'Timid'], ['せっかち', 'Hasty'], ['ようき', 'Jolly'], ['むじゃき', 'Naive'], ['まじめ', 'Serious']];
  // 性格補正：上がりやすい能力・上がりにくい能力（まじめは補正なし）
  const NATURE = { さみしがり: ['こうげき', 'ぼうぎょ'], いじっぱり: ['こうげき', 'とくこう'], やんちゃ: ['こうげき', 'とくぼう'], ゆうかん: ['こうげき', 'すばやさ'], ずぶとい: ['ぼうぎょ', 'こうげき'], わんぱく: ['ぼうぎょ', 'とくこう'], のうてんき: ['ぼうぎょ', 'とくぼう'], のんき: ['ぼうぎょ', 'すばやさ'], ひかえめ: ['とくこう', 'こうげき'], おっとり: ['とくこう', 'ぼうぎょ'], うっかりや: ['とくこう', 'とくぼう'], れいせい: ['とくこう', 'すばやさ'], おだやか: ['とくぼう', 'こうげき'], おとなしい: ['とくぼう', 'ぼうぎょ'], しんちょう: ['とくぼう', 'とくこう'], なまいき: ['とくぼう', 'すばやさ'], おくびょう: ['すばやさ', 'こうげき'], せっかち: ['すばやさ', 'ぼうぎょ'], ようき: ['すばやさ', 'とくこう'], むじゃき: ['すばやさ', 'とくぼう'] };
  MINTS.forEach(([ja, en]) => {
    const n = NATURE[ja];
    const ev = n
      ? '使うと、' + n[0] + 'が上がりやすく、' + n[1] + 'が上がりにくくなる（' + n[0] + ' 1.1倍・' + n[1] + ' 0.9倍の性格補正）。「' + ja + '」の性格と同じ補正になるが、性格そのもの（表示される性格）は変わらない。'
      : '使うと、能力の上がりやすさ・上がりにくさがなくなる（性格補正なし）。「まじめ」の性格と同じだが、性格そのもの（表示される性格）は変わらない。';
    ITEM2_ENTRIES.push({ c: 'item', ja: ja + 'ミント', en: en + ' Mint', sp: 1, cf: 3, jo: '性格「' + ja + '」＋mint', eo: 'nature "' + en + '"＋mint', ev, t: ['mint'] });
  });
  [['ＸＳ', 'XS'], ['Ｓ', 'S'], ['Ｍ', 'M'], ['Ｌ', 'L'], ['ＸＬ', 'XL']].forEach(([ja, en]) => ITEM2_ENTRIES.push({ c: 'item', ja: 'けいけんアメ' + ja, en: 'Exp. Candy ' + en, sp: 0, cf: 3, jo: '経験＋飴＋服のサイズ表記（' + en + '）', eo: 'Exp.＋candy＋' + en, ev: 'サイズが大きいほど多くの経験値がもらえる。服のサイズ表記を使った名前。', t: ['candy'] }));
  const PICNIC = [['ピンクボトル', 'Pink Bottle'], ['ブルーボトル', 'Blue Bottle'], ['イエローボトル', 'Yellow Bottle'], ['Yステンレスボトル', 'Steel Bottle (Y)'], ['Bステンレスボトル', 'Steel Bottle (B)'], ['ブロンズチタンボトル', 'Bronze Bottle'],
    ['ピンクカップ', 'Pink Cup'], ['ブルーカップ', 'Blue Cup'], ['イエローカップ', 'Yellow Cup'], ['シルバーチタンカップ', 'Silver Cup'], ['ゴールドチタンカップ', 'Gold Cup'], ['ブロンズチタンカップ', 'Bronze Cup'],
    ['きいろチェッククロス', 'Plaid Tablecloth (Y)'], ['あおチェッククロス', 'Plaid Tablecloth (B)'], ['あかチェッククロス', 'Plaid Tablecloth (R)'], ['ストライプクロス', 'Striped Tablecloth'], ['ダイヤクロス', 'Diamond Tablecloth'], ['みずたまクロス', 'Polka-Dot Tablecloth'],
    ['パープルクロス', 'Lilac Tablecloth'], ['ミントクロス', 'Mint Tablecloth'], ['ベージュクロス', 'Peach Tablecloth'], ['イエロークロス', 'Yellow Tablecloth'], ['ブルークロス', 'Blue Tablecloth'], ['ピンククロス', 'Pink Tablecloth'],
    ['シルバーピック', 'Silver Pick'], ['あかいはたピック', 'Red-Flag Pick'], ['あおいはたピック', 'Blue-Flag Pick'], ['あおボールピック', 'Blue Poké Ball Pick'], ['みどりボールピック', 'Green Poké Ball Pick'], ['あかボールピック', 'Red Poké Ball Pick'],
    ['マジカルスターピック', 'Magical Star Pick'], ['マジカルハートピック', 'Magical Heart Pick'], ['あおぞらおはなピック', 'Blue-Sky Flower Pick'], ['ゆうやけおはなピック', 'Sunset Flower Pick'],
    ['グリーンプレート', 'Green Dish'], ['オレンジプレート', 'Orange Dish'], ['レッドプレート', 'Red Dish'], ['ホワイトプレート', 'White Dish'], ['イエロープレート', 'Yellow Dish']];
  PICNIC.forEach(([ja, en]) => ITEM2_ENTRIES.push({ c: 'item', ja, en, sp: 1, cf: 3, jo: ja + '（色・柄＋品物の名前）', eo: en, ev: 'ピクニック用品。', t: ['picnic'] }));
})();

if (typeof module !== 'undefined') module.exports = ITEM2_ENTRIES;
