/*
 * ポケモンSV元ネタ推測図鑑 ― わざマシンの技（本編 No.001〜171）
 *
 * [わざマシン番号, 日本語名, 英語名, 日本語名の由来, 英語名の由来, 確からしさ(省略時 3), 補足]
 * 由来は文字列か、諸説あるときは配列。第9世代で登場した技（くさわけ・とびつく・ひやみず・ゆきげしき・
 * アイススピナー・テラバースト）は data.js の「技」に番号付きで入っているので、ここには書かない。
 */
var TM_ENTRIES = [
  [1, 'とっしん', 'Take Down', '突進（とっしん）', 'take down（倒す、レスリングのテイクダウン）'],
  [2, 'あまえる', 'Charm', '甘える', 'charm（魅了する）'],
  [3, 'うそなき', 'Fake Tears', '嘘泣き', 'fake tears（うそ泣き）'],
  [4, 'こうそくいどう', 'Agility', '高速移動', 'agility（すばやさ）'],
  [5, 'どろかけ', 'Mud-Slap', '泥かけ', 'mud（泥）＋slap（平手打ち）'],
  [6, 'こわいかお', 'Scary Face', '怖い顔', 'scary face（怖い顔）'],
  [7, 'まもる', 'Protect', '守る', 'protect（守る）'],
  [8, 'ほのおのキバ', 'Fire Fang', '炎の牙', 'fire＋fang（牙）'],
  [9, 'かみなりのキバ', 'Thunder Fang', '雷の牙', 'thunder＋fang'],
  [10, 'こおりのキバ', 'Ice Fang', '氷の牙', 'ice＋fang'],
  [11, 'みずのはどう', 'Water Pulse', '水の波動', 'water＋pulse（波動）'],
  [12, 'けたぐり', 'Low Kick', '蹴手繰り（けたぐり、相撲の決まり手）', 'low kick（ローキック）', 3, '日本語名は相撲の技、英語名は格闘技の蹴り。'],
  [13, 'アシッドボム', 'Acid Spray', 'acid（酸）＋bomb（爆弾）', 'acid＋spray（噴霧）'],
  [14, 'アクロバット', 'Acrobatics', 'acrobat（軽業）', 'acrobatics（軽業）'],
  [15, 'むしのていこう', 'Struggle Bug', '虫の抵抗（「虫の息」の言葉遊びとも）', 'struggle（もがく）＋bug', 2],
  [16, 'サイケこうせん', 'Psybeam', 'psychedelic（サイケデリック）＋光線', 'psychic＋beam'],
  [17, 'あやしいひかり', 'Confuse Ray', '怪しい光', 'confuse（混乱させる）＋ray（光線）'],
  [18, 'どろぼう', 'Thief', '泥棒', 'thief（泥棒）'],
  [19, 'チャームボイス', 'Disarming Voice', 'charm（魅了）＋voice（声）', 'disarming（心を和ませる・武装解除する）＋voice'],
  [23, 'チャージビーム', 'Charge Beam', 'charge（充電）＋beam', 'charge＋beam'],
  [24, 'ほのおのうず', 'Fire Spin', '炎の渦', 'fire＋spin（回転）'],
  [25, 'からげんき', 'Facade', '空元気（からげんき）', 'facade（見せかけ、建物の正面）'],
  [26, 'ポイズンテール', 'Poison Tail', 'poison（毒）＋tail（尻尾）', 'poison＋tail'],
  [27, 'つばめがえし', 'Aerial Ace', '燕返し（佐々木小次郎の剣技）', 'aerial（空中の）＋ace（エース）', 3, '必ず当たる技。日本語名は剣豪の秘剣、英語名は空中戦のエース。'],
  [28, 'じならし', 'Bulldoze', '地均し（じならし）', 'bulldoze（ブルドーザーでならす）'],
  [29, 'たたりめ', 'Hex', '祟り目（たたりめ、「弱り目に祟り目」）', 'hex（呪い）', 3, '状態異常の相手に威力が上がる。ことわざ「弱り目に祟り目」そのもの。'],
  [30, 'バークアウト', 'Snarl', 'bark（吠える）＋out', 'snarl（唸る）'],
  [31, 'メタルクロー', 'Metal Claw', 'metal（金属）＋claw（爪）', 'metal＋claw'],
  [32, 'スピードスター', 'Swift', 'speed＋star（星）', 'swift（すばやい）'],
  [33, 'マジカルリーフ', 'Magical Leaf', 'magical（魔法の）＋leaf（葉）', 'magical＋leaf'],
  [34, 'こごえるかぜ', 'Icy Wind', '凍える風', 'icy（氷の）＋wind'],
  [35, 'マッドショット', 'Mud Shot', 'mud（泥）＋shot', 'mud＋shot'],
  [36, 'がんせきふうじ', 'Rock Tomb', '岩石封じ', 'rock（岩）＋tomb（墓）'],
  [37, 'ドレインキッス', 'Draining Kiss', 'drain（吸い取る）＋kiss', 'draining＋kiss'],
  [38, 'ニトロチャージ', 'Flame Charge', 'nitro（ニトロ、加速）＋charge（突撃）', 'flame（炎）＋charge'],
  [39, 'ローキック', 'Low Sweep', 'low kick（ローキック）', 'low sweep（足払い）'],
  [40, 'エアカッター', 'Air Cutter', 'air＋cutter', 'air＋cutter'],
  [41, 'アシストパワー', 'Stored Power', 'assist（補助）＋power', 'stored（蓄えた）＋power'],
  [42, 'ナイトヘッド', 'Night Shade', ['night（夜）＋head（頭）', 'night＋「ヘッド」（恐ろしい顔の幻影）'], 'night shade（夜の影、植物のナス科ナイトシェードとも）', 2],
  [43, 'なげつける', 'Fling', '投げつける', 'fling（投げつける）'],
  [44, 'ドラゴンテール', 'Dragon Tail', 'dragon＋tail', 'dragon＋tail'],
  [45, 'ベノムショック', 'Venoshock', 'venom（毒）＋shock', 'venom＋shock'],
  [46, 'ゆきなだれ', 'Avalanche', '雪雪崩（ゆきなだれ）', 'avalanche（雪崩）'],
  [47, 'こらえる', 'Endure', '堪える（こらえる）', 'endure（耐える）'],
  [48, 'ボルトチェンジ', 'Volt Switch', 'volt（ボルト）＋change（交代）', 'volt＋switch（切り替え）'],
  [49, 'にほんばれ', 'Sunny Day', '日本晴れ', 'sunny day（晴れの日）'],
  [50, 'あまごい', 'Rain Dance', '雨乞い', 'rain dance（雨乞いの踊り）'],
  [51, 'すなあらし', 'Sandstorm', '砂嵐', 'sandstorm（砂嵐）'],
  [53, 'スマートホーン', 'Smart Strike', 'smart（賢い・洗練された）＋horn（角）', 'smart＋strike（一撃）'],
  [54, 'サイコショック', 'Psyshock', 'psycho＋shock', 'psychic＋shock'],
  [55, 'あなをほる', 'Dig', '穴を掘る', 'dig（掘る）'],
  [56, 'タネマシンガン', 'Bullet Seed', '種（たね）＋machine gun', 'bullet（弾丸）＋seed'],
  [57, 'みねうち', 'False Swipe', '峰打ち（刀の背で打つこと）', 'false（見せかけの）＋swipe（一撃）', 3, '相手のHPを必ず1残す。日本語名は時代劇でおなじみの手加減。'],
  [58, 'かわらわり', 'Brick Break', '瓦割り（空手の試し割り）', 'brick（れんが）＋break'],
  [59, 'しねんのずつき', 'Zen Headbutt', '思念（しねん）の頭突き', 'Zen（禅）＋headbutt（頭突き）'],
  [60, 'とんぼがえり', 'U-turn', '蜻蛉返り（すぐに引き返すこと）', 'U-turn（Uターン）', 3, '攻撃したあと手持ちに戻る。日英とも「引き返す」の意味。'],
  [61, 'シャドークロー', 'Shadow Claw', 'shadow（影）＋claw（爪）', 'shadow＋claw'],
  [62, 'イカサマ', 'Foul Play', 'いかさま（不正）', 'foul play（反則・不正行為）', 3, '相手の攻撃力でダメージを計算する技。'],
  [63, 'サイコファング', 'Psychic Fangs', 'psycho＋fang（牙）', 'psychic＋fangs'],
  [64, 'ビルドアップ', 'Bulk Up', 'build up（鍛え上げる）', 'bulk up（筋肉をつける）'],
  [65, 'エアスラッシュ', 'Air Slash', 'air＋slash（切りつけ）', 'air＋slash'],
  [66, 'のしかかり', 'Body Slam', '伸し掛かり', 'body slam（プロレスのボディスラム）'],
  [67, 'ほのおのパンチ', 'Fire Punch', '炎のパンチ', 'fire＋punch'],
  [68, 'かみなりパンチ', 'Thunder Punch', '雷パンチ', 'thunder＋punch'],
  [69, 'れいとうパンチ', 'Ice Punch', '冷凍パンチ', 'ice＋punch'],
  [70, 'ねごと', 'Sleep Talk', '寝言（ねごと）', 'sleep talk（寝言）'],
  [71, 'タネばくだん', 'Seed Bomb', '種爆弾', 'seed＋bomb'],
  [72, 'エレキボール', 'Electro Ball', 'electric＋ball', 'electro＋ball'],
  [73, 'ドレインパンチ', 'Drain Punch', 'drain（吸い取る）＋punch', 'drain＋punch'],
  [74, 'リフレクター', 'Reflect', 'reflector（反射板）', 'reflect（反射する）'],
  [75, 'ひかりのかべ', 'Light Screen', '光の壁', 'light＋screen（ついたて）'],
  [76, 'ロックブラスト', 'Rock Blast', 'rock＋blast（爆発）', 'rock＋blast'],
  [77, 'たきのぼり', 'Waterfall', '滝登り（鯉の滝登り）', 'waterfall（滝）'],
  [78, 'ドラゴンクロー', 'Dragon Claw', 'dragon＋claw', 'dragon＋claw'],
  [79, 'マジカルシャイン', 'Dazzling Gleam', 'magical＋shine（輝き）', 'dazzling（まばゆい）＋gleam（きらめき）'],
  [80, 'ゆびをふる', 'Metronome', '指を振る', 'metronome（メトロノーム、指を左右に振る動き）'],
  [81, 'くさむすび', 'Grass Knot', '草結び（草を結んで足を引っかける罠）', 'grass＋knot（結び目）'],
  [82, 'でんじは', 'Thunder Wave', '電磁波', 'thunder＋wave（波）'],
  [83, 'どくづき', 'Poison Jab', '毒突き', 'poison＋jab（ジャブ・突き）'],
  [84, 'じだんだ', 'Stomping Tantrum', '地団駄（じだんだ）を踏む', 'stomping（足踏み）＋tantrum（かんしゃく）', 3, '前のターンに技が失敗すると威力が上がる。悔しがる様子そのもの。'],
  [85, 'ねむる', 'Rest', '眠る', 'rest（休む）'],
  [86, 'いわなだれ', 'Rock Slide', '岩雪崩', 'rock slide（落石・岩崩れ）'],
  [87, 'ちょうはつ', 'Taunt', '挑発', 'taunt（挑発する）'],
  [88, 'つるぎのまい', 'Swords Dance', '剣の舞（剣舞・ハチャトゥリアンの曲名）', 'swords dance（剣の舞）'],
  [89, 'ボディプレス', 'Body Press', 'body press（プロレスのボディプレス）', 'body press'],
  [90, 'まきびし', 'Spikes', '撒菱（まきびし、忍者の道具）', 'spikes（とげ）'],
  [91, 'どくびし', 'Toxic Spikes', '毒＋撒菱（まきびし）', 'toxic（毒の）＋spikes'],
  [92, 'ふういん', 'Imprison', '封印', 'imprison（閉じ込める）'],
  [93, 'ラスターカノン', 'Flash Cannon', 'luster（光沢）＋cannon（大砲）', 'flash（閃光）＋cannon'],
  [94, 'あくのはどう', 'Dark Pulse', '悪の波動', 'dark＋pulse'],
  [95, 'きゅうけつ', 'Leech Life', '吸血', 'leech（ヒル・吸い取る）＋life'],
  [96, 'かいでんぱ', 'Eerie Impulse', '怪電波', 'eerie（不気味な）＋impulse（衝撃・パルス）'],
  [97, 'そらをとぶ', 'Fly', '空を飛ぶ', 'fly（飛ぶ）'],
  [98, 'スキルスワップ', 'Skill Swap', 'skill（特技）＋swap（交換）', 'skill＋swap'],
  [99, 'アイアンヘッド', 'Iron Head', 'iron（鉄）＋head', 'iron＋head'],
  [100, 'りゅうのまい', 'Dragon Dance', '竜の舞（龍舞）', 'dragon dance（中華圏の龍舞）'],
  [101, 'パワージェム', 'Power Gem', 'power＋gem（宝石）', 'power＋gem'],
  [102, 'ダストシュート', 'Gunk Shot', 'dust chute（ダストシュート、ごみの投入口）', 'gunk（汚れ）＋shot', 3, '日本語名は建物のごみ投入口、英語名は「汚物を撃つ」。'],
  [103, 'みがわり', 'Substitute', '身代わり', 'substitute（代わり）'],
  [104, 'てっぺき', 'Iron Defense', '鉄壁（てっぺき）', 'iron＋defense'],
  [105, 'シザークロス', 'X-Scissor', 'scissors（はさみ）＋cross（交差）', 'X（交差）＋scissor'],
  [106, 'ドリルライナー', 'Drill Run', 'drill＋liner（ライナー、直線的な打球・列車）', 'drill＋run'],
  [107, 'おにび', 'Will-O-Wisp', '鬼火（おにび）', 'will-o’-the-wisp（鬼火・狐火）'],
  [108, 'かみくだく', 'Crunch', '噛み砕く', 'crunch（噛み砕く）'],
  [109, 'トリック', 'Trick', 'trick（手品・ごまかし）', 'trick'],
  [110, 'アクアブレイク', 'Liquidation', 'aqua（水）＋break', 'liquidation（清算・一掃。liquid＝液体に掛けた語）', 2],
  [111, 'ギガドレイン', 'Giga Drain', 'giga（10億）＋drain（吸い取る）', 'giga＋drain'],
  [112, 'はどうだん', 'Aura Sphere', '波導弾（はどうだん）', 'aura（オーラ）＋sphere（球）'],
  [113, 'おいかぜ', 'Tailwind', '追い風', 'tailwind（追い風）'],
  [114, 'シャドーボール', 'Shadow Ball', 'shadow＋ball', 'shadow＋ball'],
  [115, 'りゅうのはどう', 'Dragon Pulse', '竜の波動', 'dragon＋pulse'],
  [116, 'ステルスロック', 'Stealth Rock', 'stealth（隠密）＋rock', 'stealth＋rock'],
  [117, 'ハイパーボイス', 'Hyper Voice', 'hyper＋voice', 'hyper＋voice'],
  [118, 'ねっぷう', 'Heat Wave', '熱風', 'heat wave（熱波）'],
  [119, 'エナジーボール', 'Energy Ball', 'energy＋ball', 'energy＋ball'],
  [120, 'サイコキネシス', 'Psychic', 'psychokinesis（念動力）', 'psychic（超能力）'],
  [121, 'ヘビーボンバー', 'Heavy Slam', 'heavy（重い）＋bomber（爆撃）', 'heavy＋slam（叩きつける）'],
  [122, 'アンコール', 'Encore', 'encore（アンコール）', 'encore'],
  [123, 'なみのり', 'Surf', '波乗り', 'surf（サーフィン）'],
  [125, 'かえんほうしゃ', 'Flamethrower', '火炎放射', 'flamethrower（火炎放射器）'],
  [126, '１０まんボルト', 'Thunderbolt', '10万ボルト（大きな電圧のたとえ）', 'thunderbolt（落雷）'],
  [127, 'じゃれつく', 'Play Rough', 'じゃれつく', 'play rough（乱暴に遊ぶ）'],
  [128, 'ドわすれ', 'Amnesia', 'ど忘れ', 'amnesia（記憶喪失）'],
  [129, 'めいそう', 'Calm Mind', '瞑想', 'calm mind（落ち着いた心）'],
  [130, 'てだすけ', 'Helping Hand', '手助け', 'helping hand（手助け）'],
  [131, 'かふんだんご', 'Pollen Puff', '花粉団子（ミツバチが脚に付けて運ぶ花粉の塊）', 'pollen（花粉）＋puff（ふわっとしたもの）'],
  [132, 'バトンタッチ', 'Baton Pass', 'バトンタッチ（和製英語）', 'baton pass（リレーのバトンパス）', 3, '日本語名は和製英語、英語名は本来の言い方になっている。'],
  [133, 'だいちのちから', 'Earth Power', '大地の力', 'earth＋power'],
  [134, 'きしかいせい', 'Reversal', '起死回生', 'reversal（逆転）', 3, 'HPが少ないほど威力が上がる。'],
  [135, 'れいとうビーム', 'Ice Beam', '冷凍ビーム', 'ice＋beam'],
  [136, 'エレキフィールド', 'Electric Terrain', 'electric＋field', 'electric＋terrain（地形）'],
  [137, 'グラスフィールド', 'Grassy Terrain', 'grass＋field', 'grassy＋terrain'],
  [138, 'サイコフィールド', 'Psychic Terrain', 'psycho＋field', 'psychic＋terrain'],
  [139, 'ミストフィールド', 'Misty Terrain', 'mist（霧）＋field', 'misty＋terrain'],
  [140, 'わるだくみ', 'Nasty Plot', '悪巧み', 'nasty（意地の悪い）＋plot（計略）'],
  [141, 'だいもんじ', 'Fire Blast', '大文字（京都の五山送り火「大文字」）', 'fire＋blast（爆発）', 3, '技のエフェクトが「大」の字の形の炎。'],
  [142, 'ハイドロポンプ', 'Hydro Pump', 'hydro（水）＋pump', 'hydro＋pump'],
  [143, 'ふぶき', 'Blizzard', '吹雪', 'blizzard（猛吹雪）'],
  [144, 'ほのおのちかい', 'Fire Pledge', '炎の誓い', 'fire＋pledge（誓い）'],
  [145, 'みずのちかい', 'Water Pledge', '水の誓い', 'water＋pledge'],
  [146, 'くさのちかい', 'Grass Pledge', '草の誓い', 'grass＋pledge'],
  [147, 'ワイルドボルト', 'Wild Charge', 'wild＋volt', 'wild＋charge（突撃）'],
  [148, 'ヘドロばくだん', 'Sludge Bomb', 'ヘドロ＋爆弾', 'sludge（ヘドロ）＋bomb'],
  [149, 'じしん', 'Earthquake', '地震', 'earthquake（地震）'],
  [150, 'ストーンエッジ', 'Stone Edge', 'stone＋edge（刃）', 'stone＋edge'],
  [151, 'ゴーストダイブ', 'Phantom Force', 'ghost＋dive', 'phantom（幻影）＋force'],
  [152, 'ギガインパクト', 'Giga Impact', 'giga＋impact（衝撃）', 'giga＋impact'],
  [153, 'ブラストバーン', 'Blast Burn', 'blast（爆発）＋burn（燃やす）', 'blast＋burn'],
  [154, 'ハイドロカノン', 'Hydro Cannon', 'hydro＋cannon（大砲）', 'hydro＋cannon'],
  [155, 'ハードプラント', 'Frenzy Plant', 'hard（強い）＋plant（植物）', 'frenzy（狂乱）＋plant'],
  [156, 'げきりん', 'Outrage', '逆鱗（げきりん、竜のあごの下の逆さの鱗）', 'outrage（激怒）', 3, '「逆鱗に触れる」の故事から。竜が暴れまわる技で、ドラゴンタイプ。'],
  [157, 'オーバーヒート', 'Overheat', 'overheat（過熱）', 'overheat'],
  [158, 'きあいだま', 'Focus Blast', '気合弾', 'focus（集中）＋blast'],
  [159, 'リーフストーム', 'Leaf Storm', 'leaf＋storm', 'leaf＋storm'],
  [160, 'ぼうふう', 'Hurricane', '暴風', 'hurricane（ハリケーン）'],
  [161, 'トリックルーム', 'Trick Room', 'trick room（だまし絵の部屋）', 'trick room'],
  [162, 'むしのさざめき', 'Bug Buzz', '虫の騒めき（さざめき）', 'bug＋buzz（ブンブンいう音）'],
  [163, 'はかいこうせん', 'Hyper Beam', '破壊光線', 'hyper＋beam'],
  [164, 'ブレイブバード', 'Brave Bird', 'brave＋bird', 'brave＋bird'],
  [165, 'フレアドライブ', 'Flare Blitz', 'flare（炎）＋drive（突進）', 'flare＋blitz（電撃戦）'],
  [166, 'かみなり', 'Thunder', '雷', 'thunder（雷）'],
  [167, 'インファイト', 'Close Combat', 'infight（ボクシングの接近戦）', 'close combat（接近戦）'],
  [168, 'ソーラービーム', 'Solar Beam', 'solar（太陽の）＋beam', 'solar＋beam'],
  [169, 'りゅうせいぐん', 'Draco Meteor', '流星群', 'draco（ラテン語で竜）＋meteor（流星）', 3, '日本語名は「流星群」と「竜（りゅう）」の掛け言葉にもなっている。'],
  [170, 'てっていこうせん', 'Steel Beam', '徹底光線（「鉄」と「徹底」の掛け言葉）', 'steel＋beam', 3, '自分のHPを半分削って撃つ、まさに「徹底的」な技。']
].map(([tm, ja, en, jo, eo, cf = 3, ev = '']) => ({ c: 'move', tm, ja, en, sp: tm <= 60 ? 0 : 1, cf, jo, eo, ev }));

if (typeof module !== 'undefined') module.exports = TM_ENTRIES;
