/*
 * 本編（追加コンテンツを除く）のバッグに入る道具の英語名の一覧（わざマシンを除く）
 * Bulbapedia「List of items by index number in Generation IX」の Scarlet・Violet（Ver.1.0.0 時点）の道具から作成。
 * ほかの作品・ポケモンHOME・配信がないと手に入らない、または使い道がない道具（プレート・宝玉・ぼんぐり など）は除いています。
 * 本編のポケモンで手に入る・使えると裏取りできたもの（ウルトラボール・ミツ・ロトムのカタログ）は残しています。
 * 収録状況の「道具すべて」の分母と、未収録の確認（node tools/coverage.js）に使います。
 */
var BAG_ITEMS = ("Master Ball;Ultra Ball;Great Ball;Poké Ball;Net Ball;Dive Ball;Nest Ball;Repeat Ball;Timer Ball;Luxury Ball;Premier Ball;Dusk Ball;Heal Ball;Quick Ball;Potion;Antidote;Burn Heal;Ice Heal;Awakening;Paralyze Heal;Full Restore;Max Potion;Hyper Potion;Super Potion;Full Heal;Revive;Max Revive;Fresh Water;Soda Pop;Lemonade;Moomoo Milk;Energy Powder;Energy Root;Heal Powder;Revival Herb;Ether;Max Ether;Elixir;Max Elixir;HP Up;" +
  "Protein;Iron;Carbos;Calcium;Rare Candy;PP Up;Zinc;PP Max;Guard Spec.;Dire Hit;X Attack;X Defense;X Speed;X Accuracy;X Sp. Atk;X Sp. Def;Poké Doll;Escape Rope;Sun Stone;Moon Stone;Fire Stone;Thunder Stone;Water Stone;Leaf Stone;Tiny Mushroom;Big Mushroom;Pearl;Big Pearl;Stardust;Star Piece;Nugget;Honey;Rare Bone;Shiny Stone;Dusk Stone;Dawn Stone;Oval Stone;Cheri Berry;Chesto Berry;Pecha Berry;" +
  "Rawst Berry;Aspear Berry;Leppa Berry;Oran Berry;Persim Berry;Lum Berry;Sitrus Berry;Figy Berry;Wiki Berry;Mago Berry;Aguav Berry;Iapapa Berry;Pomeg Berry;Kelpsy Berry;Qualot Berry;Hondew Berry;Grepa Berry;Tamato Berry;Occa Berry;Passho Berry;Wacan Berry;Rindo Berry;Yache Berry;Chople Berry;Kebia Berry;Shuca Berry;Coba Berry;Payapa Berry;Tanga Berry;Charti Berry;Kasib Berry;Haban Berry;Colbur Berry;Babiri Berry;Chilan Berry;Liechi Berry;Ganlon Berry;Salac Berry;Petaya Berry;Apicot Berry;" +
  "Lansat Berry;Starf Berry;Enigma Berry;Micle Berry;Custap Berry;Jaboca Berry;Rowap Berry;Bright Powder;White Herb;Quick Claw;Soothe Bell;Mental Herb;Choice Band;King's Rock;Silver Powder;Amulet Coin;Cleanse Tag;Smoke Ball;Everstone;Focus Band;Lucky Egg;Scope Lens;Metal Coat;Leftovers;Light Ball;Soft Sand;Hard Stone;Miracle Seed;Black Glasses;Black Belt;Magnet;Mystic Water;Sharp Beak;Poison Barb;Never-Melt Ice;Spell Tag;Twisted Spoon;Charcoal;Dragon Fang;Silk Scarf;" +
  "Shell Bell;Wide Lens;Muscle Band;Wise Glasses;Expert Belt;Light Clay;Life Orb;Power Herb;Toxic Orb;Flame Orb;Focus Sash;Zoom Lens;Metronome;Iron Ball;Lagging Tail;Destiny Knot;Black Sludge;Icy Rock;Smooth Rock;Heat Rock;Damp Rock;Grip Claw;Choice Scarf;Sticky Barb;Power Bracer;Power Belt;Power Lens;Power Band;Power Anklet;Power Weight;Shed Shell;Big Root;Choice Specs;Razor Claw;Fast Ball;Level Ball;Lure Ball;Heavy Ball;Love Ball;Friend Ball;" +
  "Moon Ball;Eviolite;Float Stone;Rocky Helmet;Air Balloon;Red Card;Ring Target;Binding Band;Absorb Bulb;Cell Battery;Eject Button;Normal Gem;Health Feather;Muscle Feather;Resist Feather;Genius Feather;Clever Feather;Swift Feather;Pretty Feather;Dream Ball;Balm Mushroom;Big Nugget;Pearl String;Comet Shard;Oval Charm;Shiny Charm;Weakness Policy;Assault Vest;Ability Capsule;Luminous Moss;Snowball;Safety Goggles;Roseli Berry;Kee Berry;Maranga Berry;Adventure Guide;Bottle Cap;Gold Bottle Cap;Adrenaline Orb;Ice Stone;" +
  "Terrain Extender;Protective Pads;Electric Seed;Psychic Seed;Misty Seed;Grassy Seed;Sweet Apple;Tart Apple;Throat Spray;Eject Pack;Heavy-Duty Boots;Blunder Policy;Room Service;Utility Umbrella;Exp. Candy XS;Exp. Candy S;Exp. Candy M;Exp. Candy L;Exp. Candy XL;Lonely Mint;Adamant Mint;Naughty Mint;Brave Mint;Bold Mint;Impish Mint;Lax Mint;Relaxed Mint;Modest Mint;Mild Mint;Rash Mint;Quiet Mint;Calm Mint;Gentle Mint;Careful Mint;Sassy Mint;Timid Mint;Hasty Mint;Jolly Mint;Naive Mint;Serious Mint;" +
  "Cracked Pot;Chipped Pot;Ability Patch;Rotom Phone;Sandwich;Koraidon's Poké Ball;Miraidon's Poké Ball;Tera Orb;Scarlet Book;Violet Book;Kofu's Wallet;Tiny Bamboo Shoot;Big Bamboo Shoot;Malicious Armor;Normal Tera Shard;Fire Tera Shard;Water Tera Shard;Electric Tera Shard;Grass Tera Shard;Ice Tera Shard;Fighting Tera Shard;Poison Tera Shard;Ground Tera Shard;Flying Tera Shard;Psychic Tera Shard;Bug Tera Shard;Rock Tera Shard;Ghost Tera Shard;Dragon Tera Shard;Dark Tera Shard;Steel Tera Shard;Fairy Tera Shard;Booster Energy;Ability Shield;Clear Amulet;Mirror Herb;Punching Glove;Covert Cloak;Loaded Dice;Auspicious Armor;" +
  "Leader's Crest;Baguette;Mayonnaise;Ketchup;Mustard;Butter;Peanut Butter;Chili Sauce;Salt;Pepper;Yogurt;Whipped Cream;Cream Cheese;Jam;Marmalade;Olive Oil;Vinegar;Sweet Herba Mystica;Salty Herba Mystica;Sour Herba Mystica;Bitter Herba Mystica;Spicy Herba Mystica;Lettuce;Tomato;Cherry Tomatoes;Cucumber;Pickle;Onion;Red Onion;Green Bell Pepper;Red Bell Pepper;Yellow Bell Pepper;Avocado;Bacon;Ham;Prosciutto;Chorizo;Herbed Sausage;Hamburger;Klawf Stick;" +
  "Smoked Fillet;Fried Fillet;Egg;Potato Tortilla;Tofu;Rice;Noodles;Potato Salad;Cheese;Banana;Strawberry;Apple;Kiwi;Pineapple;Jalapeño;Horseradish;Curry Powder;Wasabi;Watercress;Basil;Picnic Set;Academy Bottle;Polka-Dot Bottle;Striped Bottle;Diamond Bottle;Academy Cup;Striped Cup;Polka-Dot Cup;Flower Pattern Cup;Academy Tablecloth;Whimsical Tablecloth;Leafy Tablecloth;Spooky Tablecloth;Academy Ball;Marill Ball;Yarn Ball;Cyber Ball;Gold Pick;Silver Pick;Red-Flag Pick;" +
  "Blue-Flag Pick;Pika-Pika Pick;Winking Pika Pick;Vee-Vee Pick;Smiling Vee Pick;Blue Poké Ball Pick;Pink Bottle;Blue Bottle;Yellow Bottle;Steel Bottle (R);Steel Bottle (Y);Steel Bottle (B);Silver Bottle;Barred Cup;Diamond Pattern Cup;Fire Pattern Cup;Pink Cup;Blue Cup;Yellow Cup;Pikachu Cup;Eevee Cup;Slowpoke Cup;Silver Cup;Exercise Ball;Plaid Tablecloth (Y);Plaid Tablecloth (B);Plaid Tablecloth (R);B&W Grass Tablecloth;Battle Tablecloth;Monstrous Tablecloth;Striped Tablecloth;Diamond Tablecloth;Polka-Dot Tablecloth;Lilac Tablecloth;Mint Tablecloth;Peach Tablecloth;Yellow Tablecloth;Blue Tablecloth;Pink Tablecloth;Gold Bottle;" +
  "Bronze Bottle;Gold Cup;Bronze Cup;Green Poké Ball Pick;Red Poké Ball Pick;Party Sparkler Pick;Heroic Sword Pick;Magical Star Pick;Magical Heart Pick;Parasol Pick;Blue-Sky Flower Pick;Sunset Flower Pick;Sunrise Flower Pick;Blue Dish;Green Dish;Orange Dish;Red Dish;White Dish;Yellow Dish;Beast Ball;Red Nectar;Yellow Nectar;Pink Nectar;Purple Nectar;Rotom Catalog").split(';');

if (typeof module !== 'undefined') module.exports = BAG_ITEMS;
