/*
 * ポケモンSV元ネタ推測図鑑 ― アイテムの収録データ（追加分）
 *
 * [日本語名, 英語名, ネタバレ段階, 確からしさ, 日本語名の由来, 英語名の由来, 補足（任意）]
 * 由来は文字列か、諸説あるときは配列。第9世代で登場したアイテムは data.js に入っています。
 */
var ITEM_ENTRIES = [
  // --- ボール ---
  ['モンスターボール', 'Poké Ball', 0, 3, 'monster（怪物）＋ball。シリーズ名「ポケットモンスター」から', 'Poké（Pocket Monsters の略）＋ball'],
  ['スーパーボール', 'Great Ball', 0, 3, 'super（すごい）＋ball', 'great（すごい）＋ball'],
  ['ハイパーボール', 'Ultra Ball', 0, 3, 'hyper（超）＋ball', 'ultra（超）＋ball'],
  ['マスターボール', 'Master Ball', 2, 3, 'master（達人・支配者）＋ball', 'master＋ball'],
  ['プレミアボール', 'Premier Ball', 0, 3, 'premier（特別な、プレミア付きの）＋ball', 'premier（最高の、初公開の）＋ball', 'まとめ買いのおまけでもらえる記念のボール。'],
  ['ヒールボール', 'Heal Ball', 0, 3, 'heal（癒やす）＋ball', 'heal＋ball'],
  ['ネットボール', 'Net Ball', 0, 3, 'net（網）＋ball', 'net＋ball', 'むし・みずタイプを捕まえやすい。虫取り網・漁網のイメージ。'],
  ['ネストボール', 'Nest Ball', 0, 3, 'nest（巣）＋ball', 'nest＋ball', 'レベルの低いポケモンを捕まえやすい。巣立ち前のイメージ。'],
  ['ダイブボール', 'Dive Ball', 0, 3, 'dive（潜る）＋ball', 'dive＋ball'],
  ['ダークボール', 'Dusk Ball', 0, 3, 'dark（暗い）＋ball', 'dusk（夕暮れ）＋ball', '夜や洞窟で捕まえやすい。'],
  ['タイマーボール', 'Timer Ball', 0, 3, 'timer＋ball', 'timer＋ball', 'ターンが経つほど捕まえやすい。'],
  ['クイックボール', 'Quick Ball', 0, 3, 'quick（すばやい）＋ball', 'quick＋ball', '戦闘の最初に投げると捕まえやすい。'],
  ['リピートボール', 'Repeat Ball', 0, 3, 'repeat（くり返す）＋ball', 'repeat＋ball', '捕まえたことのあるポケモンに効く。'],
  ['ゴージャスボール', 'Luxury Ball', 0, 3, 'gorgeous（豪華な）＋ball', 'luxury（ぜいたく）＋ball'],
  ['レベルボール', 'Level Ball', 1, 3, 'level＋ball', 'level＋ball'],
  ['ルアーボール', 'Lure Ball', 1, 3, 'lure（釣りの疑似餌ルアー）＋ball', 'lure＋ball'],
  ['ヘビーボール', 'Heavy Ball', 1, 3, 'heavy（重い）＋ball', 'heavy＋ball'],
  ['ラブラブボール', 'Love Ball', 1, 3, 'ラブラブ（仲睦まじい）＋ball', 'love＋ball'],
  ['フレンドボール', 'Friend Ball', 1, 3, 'friend（友達）＋ball', 'friend＋ball'],
  ['ムーンボール', 'Moon Ball', 1, 3, 'moon（月）＋ball', 'moon＋ball', '「つきのいし」で進化するポケモンを捕まえやすい。'],
  ['スピードボール', 'Fast Ball', 1, 3, 'speed＋ball', 'fast（速い）＋ball'],
  ['ドリームボール', 'Dream Ball', 1, 3, 'dream（夢）＋ball', 'dream＋ball', 'ねむり状態のポケモンを捕まえやすいボール。本作ではパルデア図鑑を360種類登録したごほうびなどでもらえる。'],
  ['ウルトラボール', 'Beast Ball', 3, 3, ['ultra（超）＋ball。ウルトラビースト（別の世界から来たポケモン）用のボール', 'ウルトラホール（別の世界への穴）から'], 'Ultra Beast（ウルトラビースト）の beast＋ball', 'ウルトラビーストを捕まえやすく、ほかのポケモンは捕まえにくいボール。本作ではパルデア図鑑を400種類登録したごほうびでもらえる。英語の Ultra Ball は日本語の「ハイパーボール」のことなので、英語では Beast Ball と別の名前になっている。'],

  // --- 回復・育成 ---
  ['キズぐすり', 'Potion', 0, 3, '傷薬（きずぐすり）', 'potion（水薬）'],
  ['いいキズぐすり', 'Super Potion', 0, 3, 'いい（良い）＋傷薬', 'super＋potion'],
  ['すごいキズぐすり', 'Hyper Potion', 0, 3, 'すごい＋傷薬', 'hyper＋potion'],
  ['まんたんのくすり', 'Max Potion', 1, 3, '満タン（いっぱい）の薬', 'max（最大）＋potion'],
  ['かいふくのくすり', 'Full Restore', 1, 3, '回復の薬', 'full（完全）＋restore（回復）'],
  ['げんきのかけら', 'Revive', 0, 3, '元気の欠片（かけら）', 'revive（生き返らせる）'],
  ['げんきのかたまり', 'Max Revive', 1, 3, '元気の塊（かたまり）', 'max＋revive'],
  ['なんでもなおし', 'Full Heal', 0, 3, '何でも治し', 'full＋heal'],
  ['どくけし', 'Antidote', 0, 3, '毒消し', 'antidote（解毒剤）'],
  ['まひなおし', 'Paralyze Heal', 0, 3, '麻痺治し', 'paralyze（麻痺させる）＋heal'],
  ['ねむけざまし', 'Awakening', 0, 3, '眠気覚まし', 'awakening（目覚め）'],
  ['やけどなおし', 'Burn Heal', 0, 3, '火傷治し', 'burn（やけど）＋heal'],
  ['こおりなおし', 'Ice Heal', 0, 3, '氷治し', 'ice＋heal'],
  ['ピーピーエイド', 'Ether', 1, 3, 'PP（技を使える回数）＋aid（助け）', ['ether（エーテル、古い麻酔薬・天上の霊気）', '回復薬の名に霊薬の名前を使う RPG の伝統']],
  ['ピーピーマックス', 'Max Elixir', 1, 3, 'PP＋max', ['max＋elixir（霊薬・不老不死の薬）', '錬金術の「エリクサー」']],
  ['ふしぎなアメ', 'Rare Candy', 1, 3, '不思議な飴', 'rare（珍しい）＋candy（飴）'],
  ['とくせいカプセル', 'Ability Capsule', 1, 3, '特性＋capsule', 'ability（特性）＋capsule'],
  ['とくせいパッチ', 'Ability Patch', 2, 3, '特性＋patch（貼り薬・修正）', 'ability＋patch'],
  ['ぎんのおうかん', 'Bottle Cap', 1, 3, '銀の王冠（瓶の栓の「王冠」と、王様の冠の掛け言葉）', 'bottle cap（瓶の栓）', '日本語では瓶の栓を「王冠」と呼ぶため、英語名は瓶の栓そのものになっている。'],
  ['きんのおうかん', 'Gold Bottle Cap', 2, 3, '金の王冠', 'gold＋bottle cap'],

  // --- 進化の道具 ---
  ['ほのおのいし', 'Fire Stone', 0, 3, '炎の石', 'fire＋stone'],
  ['みずのいし', 'Water Stone', 0, 3, '水の石', 'water＋stone'],
  ['かみなりのいし', 'Thunder Stone', 0, 3, '雷の石', 'thunder＋stone'],
  ['リーフのいし', 'Leaf Stone', 0, 3, 'leaf（葉）の石', 'leaf＋stone'],
  ['こおりのいし', 'Ice Stone', 1, 3, '氷の石', 'ice＋stone'],
  ['つきのいし', 'Moon Stone', 0, 3, '月の石', 'moon＋stone'],
  ['たいようのいし', 'Sun Stone', 1, 3, '太陽の石', 'sun＋stone'],
  ['ひかりのいし', 'Shiny Stone', 1, 3, '光の石', 'shiny（輝く）＋stone'],
  ['やみのいし', 'Dusk Stone', 1, 3, '闇の石', 'dusk（夕暮れ）＋stone'],
  ['めざめいし', 'Dawn Stone', 1, 3, '目覚め石', 'dawn（夜明け）＋stone', '「やみのいし＝夕暮れ」と対になる英語名。'],
  ['おうじゃのしるし', "King's Rock", 1, 3, '王者の印', "king's（王の）＋rock（宝石）", 'ヤドンをヤドキングに進化させる。'],
  ['メタルコート', 'Metal Coat', 1, 3, 'metal＋coat（被膜）', 'metal＋coat'],
  ['あまーいりんご', 'Sweet Apple', 1, 3, '甘ーいりんご', 'sweet＋apple', 'カジッチュをタルップルに進化させる。'],
  ['すっぱいりんご', 'Tart Apple', 1, 3, '酸っぱいりんご', 'tart（酸っぱい）＋apple', 'カジッチュをアップリューに進化させる。'],
  ['われたポット', 'Cracked Pot', 1, 3, '割れたポット', 'cracked（ひびの入った）＋pot', 'ヤバチャの進化に使う。英語の cracked pot は「変わり者（crackpot）」とも掛かる。'],
  ['かけたポット', 'Chipped Pot', 1, 3, '欠けたポット', 'chipped（欠けた）＋pot'],

  // --- バトルの持ち物 ---
  ['たべのこし', 'Leftovers', 0, 3, '食べ残し', 'leftovers（食べ残し）'],
  ['こだわりスカーフ', 'Choice Scarf', 1, 3, 'こだわり＋scarf', 'choice（選択）＋scarf', '同じ技しか出せなくなる代わりに素早さが上がる。'],
  ['こだわりハチマキ', 'Choice Band', 1, 3, 'こだわり＋鉢巻き', 'choice＋band（鉢巻き）'],
  ['こだわりメガネ', 'Choice Specs', 1, 3, 'こだわり＋眼鏡', 'choice＋specs（眼鏡 spectacles）'],
  ['きあいのタスキ', 'Focus Sash', 1, 3, '気合の襷（たすき）', 'focus（集中）＋sash（肩帯）'],
  ['きあいのハチマキ', 'Focus Band', 1, 3, '気合の鉢巻き', 'focus＋band'],
  ['いのちのたま', 'Life Orb', 1, 3, '命の玉', 'life＋orb（宝珠）'],
  ['とつげきチョッキ', 'Assault Vest', 1, 3, '突撃＋チョッキ（ベスト）', 'assault（突撃）＋vest', '攻撃技しか出せない代わりに特防が上がる。'],
  ['ゴツゴツメット', 'Rocky Helmet', 1, 3, 'ごつごつ＋helmet', 'rocky（ごつごつした）＋helmet'],
  ['くろいヘドロ', 'Black Sludge', 1, 3, '黒いヘドロ', 'black＋sludge（ヘドロ）'],
  ['じゃくてんほけん', 'Weakness Policy', 1, 3, '弱点保険', 'weakness（弱点）＋policy（保険証券）'],
  ['だっしゅつボタン', 'Eject Button', 1, 3, '脱出＋button', 'eject（射出する）＋button'],
  ['あつぞこブーツ', 'Heavy-Duty Boots', 1, 3, '厚底ブーツ', 'heavy-duty（頑丈な）＋boots'],
  ['ひかりのねんど', 'Light Clay', 1, 3, '光の粘土', 'light＋clay', '「リフレクター」「ひかりのかべ」を長持ちさせる。'],
  ['ルームサービス', 'Room Service', 1, 3, 'room service（ホテルのルームサービス）', 'room service', '「トリックルーム」のときに素早さが下がる、部屋にちなんだ持ち物。'],
  ['しろいハーブ', 'White Herb', 1, 3, '白いハーブ', 'white＋herb'],
  ['メンタルハーブ', 'Mental Herb', 1, 3, 'mental＋herb', 'mental＋herb'],
  ['パワフルハーブ', 'Power Herb', 1, 3, 'powerful＋herb', 'power＋herb'],
  ['ばんのうがさ', 'Utility Umbrella', 1, 3, '万能傘（ばんのうがさ）', 'utility（便利な）＋umbrella', '晴れや雨の影響を受けなくなる。'],
  ['ふうせん', 'Air Balloon', 1, 3, '風船', 'air＋balloon', 'じめん技が当たらなくなる。'],
  ['しんかのきせき', 'Eviolite', 1, 3, '進化の輝石（きせき）。「奇跡」とも掛かる', 'evolution（進化）＋-ite（鉱物の語尾）', '進化前のポケモンの防御と特防が上がる。'],

  // --- きのみ ---
  ['オレンのみ', 'Oran Berry', 0, 2, 'orange（オレンジ）', 'orange', '見た目は青い実。'],
  ['オボンのみ', 'Sitrus Berry', 1, 2, ['文旦（ぶんたん・ボンタン）', 'お盆（おぼん）'], 'citrus（柑橘）'],
  ['ラムのみ', 'Lum Berry', 1, 3, ['プラム（plum＝スモモ）の頭の「プ」を取った形', 'ラム（お酒）の響き'], 'plum（スモモ）の頭の p を取った形', '見た目も中国のスモモ（ウメの仲間）に似ている。'],
  ['クラボのみ', 'Cheri Berry', 0, 3, 'さくらんぼ（桜桃）の並べ替え', 'cherry（さくらんぼ）'],
  ['カゴのみ', 'Chesto Berry', 0, 2, ['籠（かご）。英語の chestnut に入っている chest（箱）を、日本語で「籠」に置き換えた言葉遊び', '籠のような網目模様の見た目'], 'chestnut（クリ）', '見た目はクワイ（英語で Chinese water chestnut）に似ている。'],
  ['モモンのみ', 'Pecha Berry', 0, 3, '桃（もも）', 'peach（桃）'],
  ['チーゴのみ', 'Rawst Berry', 0, 3, 'いちご（苺）の並べ替え', ['strawberry（イチゴ）の一部', 'raw（生の）＋roast（焼く。やけどを治す実）']],
  ['ナナシのみ', 'Aspear Berry', 0, 3, ['梨（なし）＋名無し（ななし）'], 'Asian pear（アジアのナシ＝和梨）を縮めた形'],
  ['ヒメリのみ', 'Leppa Berry', 0, 2, '姫林檎（ひめりんご）', 'apple（りんご）の並べ替え'],
  ['キーのみ', 'Persim Berry', 1, 3, ['柿（かき）の響き', 'kiwi（キウイ）'], 'persimmon（柿）']
].map(([ja, en, sp, cf, jo, eo, ev = '']) => ({ c: 'item', ja, en, sp, cf, jo, eo, ev }));

if (typeof module !== 'undefined') module.exports = ITEM_ENTRIES;
